### ISSUE TITLE
Stories

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/shannon-trust-website#10]
__Related issue(s)__

The blog post that makes up the collection is here: #9 

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [x] Create Stories page https://www.figma.com/file/vC6iqpWqeTJSPkM0Lswcfp/Shannon-Trust---Website?node-id=214%3A331
- [x] CMS collections: 
    - [x] Collection of all 'story' posts #9 
    - [x] Get feed of 4 posts then load 4 more on click
    - [x] Always list in order of most recently published (but prioritise featured ones)
- [x] Filter includes 6 categories/tags
    - [x] User can only select one at a time
    - [x] Clicking a tag will get any stories that have that tag
- [x] Please refer to text limits in Figma comments
- [x] Please follow prototype links in Figma

**Comment by RamyAlshurafa** [comment]
https://shannon-trust-website.webflow.io/stories
