### ISSUE TITLE
Wrong volunteer locations appearing on volunteer form

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#101]
### Please select the priority level by adding one of the following labels to this issue?

Priority-2 (High e.g. Core functionality is not working)

### Describe the bug and the expected behaviour.

We've had someone apply for a volunteer role that we don't actually have available. Looking at the form on the website, it seems like when you initially view the 'reading coach' roles, the locations for the 'community project support' role come up. However, if I select 'community project support' and then select 'reading coach', the correct locations appear.

Not sure why this is happening, but can you look into this, please and fix?

### Steps To Reproduce

1. Go to https://www.shannontrust.org.uk/volunteer
2. Scroll to 'apply'
3. Select 'in communities' and 'reading coaches'
4. See list of locations
5. Select 'community project support' and see list of locations
6. Select 'reading coaches' and view the list of locations again to see change

### Screenshots or a link to a Loom Recording

![Screenshot (253)](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/e89c0364-5707-4afd-86bc-74c19750c74d)

![Screenshot (254)](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/b24654f0-efbc-43e7-836f-cc14f5855013)

![Screenshot (255)](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/07557dee-edbe-4d67-9883-4a76d00eda32)

### What browsers are you seeing the problem on?

Chrome

**Comment by cyberteenie** [comment]
Hi @ShannonTrust thanks for flagging this with us. We are looking into it!

**Comment by RamyAlshurafa** [comment]
Hey @ShannonTrust 
this is fixed now, can you check please?

**Comment by ShannonTrust** [comment]
Thanks, @RamyAlshurafa. All looks good from our end.
