### ISSUE TITLE
Remove criminal convictions question from volunteer form

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#102]
### Is your feature / client request related to a problem? Please describe.

On our current volunteer form, we ask applicants if they have a criminal record. We are a Ban the Box employer so we shouldn't be asking for this. Can we remove this question from the volunteer application form, please?

### Screenshots or a link to a Loom Recording

![Screenshot (256)](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/c2bff4ab-80fb-404a-a4f0-d73f0ee1688e)

**Comment by cyberteenie** [comment]
@ShannonTrust - yes, will do!

**Comment by RamyAlshurafa** [comment]
Hey @ShannonTrust 
We have removed the question and deployed to the staging website https://shannon-trust.webflow.io/volunteer
can you check and confirm if you are happy to deploy to prodcution

**Comment by ShannonTrust** [comment]
Thanks, @RamyAlshurafa. Can we also remove the question about court cases and the 'yes' box, please? And then the copy under 'criminal record declaration', can we change to this:

We welcome applications to volunteer from people with lived experience of the criminal justice system and do not routinely ask for details of any criminal convictions.  Some of our volunteer roles do require prison security clearance and/ or DBS checks, so we may need to ask for details of any relevant criminal convictions before starting to volunteer in these positions.

**Comment by redahaq** [comment]
Hi @ShannonTrust. I've picked this up from @RamyAlshurafa. 

Yes of course; I've made the requested updates and deployed to staging https://shannon-trust.webflow.io/volunteer. Please can you review and confirm you're happy with it, and then we'll deploy the site to production. 

Best, Reda

**Comment by ShannonTrust** [comment]
Thanks for making the changes, @redahaq. The form looks good, but I've noticed that something else has appeared on the page that shouldn't be there. I've taken a screenshot to show the white writing that can be seen above the form. Please can this be removed before it's deployed to the main site.

![Screenshot (257)](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/e5b96f5a-c36d-4e3b-8e24-98ae55069cc3)

**Comment by redahaq** [comment]
Hi @ShannonTrust. Thank you! Sorry about that, I've removed it and deployed to the main site as requested.
