### ISSUE TITLE
Change Twitter logo to X in footer

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#103]
### Is your feature / client request related to a problem? Please describe.

There's no major rush with this, but can you change the Twitter logo in the footer of the website to the X logo, please?

### Screenshots or a link to a Loom Recording

![Screenshot (260)](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/9f28a659-a64f-4e56-aeb4-e512cf969a00)

**Comment by cyberteenie** [comment]
Will do!

**Comment by ShannonTrust** [comment]
Thanks, @redahaq - all looks good!
