### ISSUE TITLE
New page for legacy gifts

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#104]
### Is your feature / client request related to a problem? Please describe.

This is not a task for now, but next year we want to add a new page around legacy gifts. We're likely to want this doing in Q1 of 2024, but we don't have a plan just yet. Amy will provide more detail in January.

**Comment by cyberteenie** [comment]
Ok. Thanks for the heads-up. I will put this into the backlog. Let us know when you are ready to discuss.

**Comment by ShannonTrust** [comment]
Hey @cyberteenie, we are starting to look at developing the legacy page now, as well as making a few other changes to the fundraising pages. Would we be able to set up a meeting to discuss these further and decide on the look, please?

**Comment by cyberteenie** [comment]
@ShannonTrust absolutely!
I am actually away until May 17, but I will coordinate with Joe to meet and discuss with you!

**Comment by thejoefriel** [comment]
Hey @ShannonTrust here's the page on staging for your review: https://shannon-trust.webflow.io/leave-a-gift-in-your-will

Things to decide:
- What heading image you would like 
- What background image your want for gift makes a difference
- What background images you would want for the Steps

Look forward to hearing your feedback.

**Comment by ShannonTrust** [comment]
Hey @thejoefriel, thanks for doing this so quickly. Amy and I have reviewed and there were a couple of things that came up that we would like changing:

- Could you move the quote carousel to underneath 'how your gift makes a difference' please?
- We're not too sure on the 3 boxes under 'how to leave a gift...' - could you try putting it in 3 boxes in a row, please? I'm thinking something similar to what we have on our employee benefits page (see screenshot below), this might not work, so we welcome your thoughts on how to lay this out
- I'll take a look at photos and come back to you - we recently had some new photography done and I need to go through where we need to make updated across the whole site
- There are also some copy edits, but I can sort those out myself before it goes live

Employee benefit example:
![Screenshot (301)](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/dcbc06e9-08be-4493-b41e-cdf0e1e79ced)

**Comment by ShannonTrust** [comment]
Hey @thejoefriel, are we able to have an update on this, please? Thank you.

**Comment by cyberteenie** [comment]
This will be done by the end of the day @ShannonTrust !

**Comment by ShannonTrust** [comment]
Thanks, @cyberteenie. This looks great and we're really happy with the new structure. Please go ahead and remove the coloured boxes and make it live. Thank you

**Comment by cyberteenie** [comment]
Great! That's live now :)

**Comment by ShannonTrust** [comment]
Thanks @cyberteenie. It's not coming up in the drop down menu under 'how you can help' can you add it here, please?
