### ISSUE TITLE
Volunteer page updates

### ISSUE THREAD

**Issue by cyberteenie** [yalla-coop/shannon-trust-website#105]
### Is your feature / client request related to a problem? Please describe.

Shannon Trust will be moving to Hireful to manage their volunteer hiring.

### Describe the solution you'd like
- Follow the same logic as with staff hiring page
- All roles should now only include one button with the copy "Find out more and apply"
- A new section should be created called "Business Support" for another role that doesn't fall into the current categories
- The recruitment and training section can be removed, but the closing date for applications as well as the dates for the training sessions should be moved into the description copy at the top of the prison roles section.
- The apply section with the form should be hidden (but not deleted in case they want to revert)
- The digital reading coach currently links to the app, so that will remain an outlier and not link to Hireful. For consistency, I think we can also only have one button.

This needs to be completed on Monday January 22 in the morning.

**Comment by cyberteenie** [comment]
Dates for updated copy are:
Closing date: 10th May

Successful applicants will be invited to interview during the weeks commencing 13th and 20th May

Training sessions: 13th, 20th, 27th June and 4th July

**Comment by cyberteenie** [comment]
Sent Amy and Megan an email requesting the Hireful links for each role.

**Comment by cyberteenie** [comment]
Moved to Monday 5 February
Will get the links before.

**Comment by cyberteenie** [comment]
Hi @ShannonTrust - sorry I missed this message last week! We will get on this asap.

**Comment by ShannonTrust** [comment]
Hi @cyberteenie, sorry can you hold off for a bit more, please? We're making some other changes and I need to map out what this is actually going to look like on the website and I don't want you to do any unnecessary changes when it might change again - I'll keep you informed when I know more.

**Comment by cyberteenie** [comment]
No problem - let us know when you are ready @ShannonTrust

**Comment by ShannonTrust** [comment]
Hi @cyberteenie, can we go ahead with the changes to the volunteer page now, please? 

I've confirmed with Amy what changes we would like:
- The prison role descriptions will all stay the same but the 'check locations and apply' button can change to 'find out more and apply', linking to the Hireful page 
- Under the community roles, can we remove the digital reading coach and community project support roles. We want to keep the reading coach role and have this link to Hireful as well
- We will hide the application form
- Can the 'recruitment and training' section be moved to above the FAQs, please?
- I'm going to change the 'corporate volunteering' section to 'business support volunteering' so we don't need you to add an extra section like we had discussed

Any questions, let me know. I'm going to be an annual leave 7 to 18 March, but I'll let Amy L know to look out for anything and she can share it with Amy B.

**Comment by cyberteenie** [comment]
@ShannonTrust - great! We will move forward on this next week.
I will ask Ramy have a look to ensure that we get any questions across to you before you are off on leave! Thanks!

**Comment by cyberteenie** [comment]
Closing as done
