### ISSUE TITLE
Blog post headings and 'posted by' are indented

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#107]
### Please select the priority level by adding one of the following labels to this issue?

Priority-3 (Normal e.g. Functionality is not working for a subset of users)

### Describe the bug and the expected behaviour.

I was uploading a new blog post and while I was checking it I noticed that where the date is, that's now indented. I checked on the other blog posts and some of the headings are also indented. Could you look at why this is, please?

### Steps To Reproduce

https://www.shannontrust.org.uk/stories

https://www.shannontrust.org.uk/news-and-views

### Screenshots or a link to a Loom Recording

![Screenshot (262)](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/23bb1462-6978-4d56-9289-5ea3f5824b73)
![Screenshot (263)](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/b9a0ecf7-d527-4f53-b05c-1f4d2c82c801)

### What browsers are you seeing the problem on?

Chrome

**Comment by cyberteenie** [comment]
Will have a look and get back to you!

**Comment by ShannonTrust** [comment]
Ramy has now fixed this.
