### ISSUE TITLE
Resource order form default settings

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#109]
### Please select the priority level by adding one of the following labels to this issue?

Priority-4 (Low e.g. Content is not perfectly aligned)

### Describe the bug and the expected behaviour.

We've been having some orders come through from the website where some people aren't putting the correct establishment with their order. It's currently set as HMP Altcourse as the default and there are people obviously missing this and not changing it. This then adds more work for us to making sure it's the correct prison we need to send the resources to. Is there a way to have this field blank as a default and adding a red asterisk to make it obvious that it's mandatory to fill it in? 

### Steps To Reproduce

Go to https://www.shannontrust.org.uk/order-resources
Scroll to the form and see 'establishment'

### Screenshots or a link to a Loom Recording

![Screenshot (275)](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/d135eccf-2c3f-4b75-97be-6a12e60d5c5c)

### What browsers are you seeing the problem on?

Chrome

**Comment by cyberteenie** [comment]
no problem @ShannonTrust . Will update that for you!

**Comment by cyberteenie** [comment]
New default field has been set up.
Ramy to add Javascript to ensure that people do not submit form without selecting an establishment (add error message and red asterix -*)

**Comment by RamyAlshurafa** [comment]
Done, can you check @ShannonTrust

**Comment by ShannonTrust** [comment]
Thanks for sorting, @RamyAlshurafa
