### ISSUE TITLE
Some sections are not aligned on mobile

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#110]
### Please select the priority level by adding one of the following labels to this issue?

Priority-3 (Normal e.g. Functionality is not working for a subset of users)

### Describe the bug and the expected behaviour.

I've been doing a mobile check of the website and there are a couple of things that are out of place. 

- Impact page: the reports are stacked rather than in a line on mobile, and the copy on the photo under the reports isn't central to the page
- Turning Pages reading manuals: all the subheadings don't seem to fit in the blue mark properly
- Numeracy: same as above, the headings don't seem to fit properly
- Our history: on the timeline, 'key Shannon Trust moments', all the dates have moved so that it's no longer all in line
- New and views: the social media feeds aren't appearing for some reason
- Donate, fundraise, fundraise your way, challenges and events: on all of these pages, where it has 'how your donations make a difference' the blue mark doesn't fit the text

### Steps To Reproduce

On mobile:

- https://www.shannontrust.org.uk/impact
- https://www.shannontrust.org.uk/turning-pages
- https://www.shannontrust.org.uk/numeracy
- https://www.shannontrust.org.uk/news-and-views
- https://www.shannontrust.org.uk/donate
- https://www.shannontrust.org.uk/fundraise
- https://www.shannontrust.org.uk/fundraise-your-way
- https://www.shannontrust.org.uk/challenges-events

### Screenshots or a link to a Loom Recording

![Screenshot_20240117-143721](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/5e8af2a2-77df-4e48-9f24-194a6a3b5c3a)
![Screenshot_20240117-143847](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/c8225ea0-a095-49bc-afaa-f640c2db900f)
![Screenshot_20240117-144003](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/7731ba69-6863-4b14-a38b-f0ffca971031)
![Screenshot_20240117-144233](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/cb5f0b21-3ab1-4be6-86b2-98169bd57577)
![Screenshot_20240117-144251](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/0200f9b3-fb48-4831-a403-a20669b84da9)
![Screenshot_20240117-143539](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/ca97361d-e0cb-4b64-8e03-7fcda33c3af0)
![Screenshot_20240117-143710](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/02b13969-c914-4174-b3cd-dbef5b42ff6e)
![Screenshot_20240117-143745](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/c7327f45-34f9-4c3e-87f7-bbe346a1a377)
![Screenshot_20240117-143822](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/5ada6700-d948-42b7-9f27-21e7bb93408e)
![Screenshot_20240117-144033](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/f762f573-fd5d-4550-92d2-e360bcc43661)
![Screenshot_20240117-143716](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/f1ca39f9-6261-41d3-9244-d979ec98b73c)

### What browsers are you seeing the problem on?

Chrome

**Comment by redahaq** [comment]
Hi @ShannonTrust, thanks very much for flagging these issues. I've gone through and made the fixes, would you mind reviewing please? 

Just a note that the social media feeds won't appear on this staging link so you can review those once you're happy with the rest of the changes and we've pushed to the site to production. Thank you!

https://shannon-trust.webflow.io/

**Comment by ShannonTrust** [comment]
Thanks, @redahaq. The only thing I'm still unsure about is the timeline on 'our history' page. I don't think the dates are normally central. On the web version, the dates are next to the copy:

![Screenshot (278)](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/79e09202-5ccb-40af-8968-9bc62a9d72a2)

Everything else looks good.

**Comment by redahaq** [comment]
Thanks for clarifying @ShannonTrust; I've left-aligned the dates on mobile as well now. Are you happy for the issue to be closed?

**Comment by ShannonTrust** [comment]
Perfect. Thanks, @redahaq
