### ISSUE TITLE
Out of stock items on order form

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#111]
### Is your feature / client request related to a problem? Please describe.

Is there a way to stop people ordering certain items on the order resource form when they are out of stock. We've been putting a note on there to say 'out of stock, do not order' but people are still ordering them, which messes up our records. Is there an easy way for me to stop people selecting an items that's out of stock?  

### Screenshots or a link to a Loom Recording

![Screenshot (280)](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/56a07992-5593-4a36-a488-af2b74534780)

**Comment by cyberteenie** [comment]
@ShannonTrust - will talk this through with Ramy and get back to you!

**Comment by cyberteenie** [comment]
Ramy to make a Loom to show how to disable an input

**Comment by RamyAlshurafa** [comment]
Hey @ShannonTrust 
this is done now, 
so when you want to disable an input, you can click on it, and then from style selector type in "disabled", then you have to publish

https://www.loom.com/share/bc96ce039330446aa65525b43749b910
let me know if any issue

**Comment by ShannonTrust** [comment]
Perfect, thank you @RamyAlshurafa. All makes sense.
