### ISSUE TITLE
Pre-populated items on the order form

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#113]
### Please select the priority level by adding one of the following labels to this issue?

Priority-3 (Normal e.g. Functionality is not working for a subset of users)

### Describe the bug and the expected behaviour.

We had an email this morning from one of our facilitators saying when they went to submit an order, some items had been pre-populated on the order form and it was items they would never order. I don't have a screenshot of what this looked like and when I looked myself nothing came up, but do you know what this error is? 

This was the email for a bit more context:

I was putting my order through this morning for the CMI books again and a few other TP resources but I noticed just before I hit submit that parts of the form were pre-populated (not from my previous order - there were female flyers) and those item boxes were highlighted blue. I haven't seen that on the form before. I went through and removed the items I wasn't requesting but the boxes were still blue.

Just thought I'd mention it. I followed the link as usual but the form definitely looked different. I wondered if it might account for possible mis-orders? If I hadn't double checked I would have requested stock I hadn't clicked on.

### Steps To Reproduce

https://www.shannontrust.org.uk/order-resources

**Comment by cyberteenie** [comment]
@ShannonTrust - will look into this!

**Comment by RamyAlshurafa** [comment]
Hey @ShannonTrust 
i have done some investigations and found a poosible cause to this issue: when user scroll on a number input it increment/decrement the value, i disabled this default behaviour now, so that should fix it
