### ISSUE TITLE
Making sure only email addresses are entered to the resource form

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#114]
### Ask your question here.

Some of our team have been looking at sorting out confirmation emails following someone making an order on our website, but an issue has come up where not everyone inputs their email to the form. Do you know if it is possible to only allow email addresses into the 'requested by' section at the top of the form? And to make this compulsory? Some people are putting their names in, so they won't get the confirmation email.

### Screenshots or a link to a Loom Recording

![Screenshot (294)](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/15a4f174-801f-45b9-9ba7-c31c44189e3e)

**Comment by cyberteenie** [comment]
Hey @ShannonTrust - will get back to you on this asap!

**Comment by RamyAlshurafa** [comment]
Hey @ShannonTrust 
this is fixed now, can you check please?

**Comment by ShannonTrust** [comment]
Thanks, @RamyAlshurafa. All looks good.
