### ISSUE TITLE
Date and author missing from blog posts

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#117]
### Please select the priority level by adding one of the following labels to this issue?

Priority-4 (Low e.g. Content is not perfectly aligned)

### Describe the bug and the expected behaviour.

I was just posting a new blog post and noticed that although I had put in the author and date in editor, it's no longer showing up on the front end of the website when I hit publish. I've looked myself to see if I can fix it, but can't figure it out. Could you look at some point to see how we can get it back, please? It was usually underneath the title.

### Screenshots or a link to a Loom Recording

![Screenshot (295)](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/d508f776-79a4-44c3-8541-fca51d5215e4)

**Comment by cyberteenie** [comment]
@ShannonTrust - will look into this!

**Comment by ShannonTrust** [comment]
Thanks, @redahaq. That's great. Please publish to live site.
