### ISSUE TITLE
Order form query 

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#118]
### Ask your question here.

We have added a couple of new items to the order resource form, but they are only for when a learner finishes one of our programmes. I was speaking to the team and they asked if there was a way for us ensure only finishers get the items and prisons aren't holding stock. 

One suggestion was if there could be a free textbox where we ask for the prisoner number so we can check it against our own records. But I wanted to bring the question to you to see what would be possible and from a user experience, what would you suggest? 

### Screenshots or a link to a Loom Recording

![Screenshot (296)](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/c70fc5fc-2409-4e7f-a796-48597218db86)
![Screenshot (297)](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/3be2affa-0dc5-42c5-bc05-d1e4b68e711a)

**Comment by cyberteenie** [comment]
@ShannonTrust - we will have a chat about this internally and will get back to you!

**Comment by thejoefriel** [comment]
Hey @ShannonTrust thanks for sharing this. Yeah it's an interesting one! I reckon it might be easiest if we hop on a call to map out the potential user journey here. 

Here's my current availability: https://calendar.app.google/CeeQ2WWaT2R4Lrim6

**Comment by ShannonTrust** [comment]
Hey @thejoefriel, I was just wondering if you could give us an update on what we discussed when we met a couple of weeks ago?

**Comment by thejoefriel** [comment]
Hey @ShannonTrust - I'm very sorry. I've only just had a chance to look at this today. Here's the [proto](https://www.figma.com/proto/vC6iqpWqeTJSPkM0Lswcfp/Shannon-Trust-Website---Design-System-and-Wireframes?type=design&node-id=3979-6913&t=vhaY028nASYkZVcA-1&scaling=scale-down&page-id=214%3A2&starting-point-node-id=3979%3A6913&show-proto-sidebar=1&mode=design) 

and here's a video providing context: https://www.loom.com/share/06d28d42f3994b26878ffbb18982fc2f

**In terms of flow:**
- User types in IDs for each learner
- Helper text shows the number of IDs they have provided
- On submit:
    - we calculate the number based on the number of IDs and that informs the quantity
    - we also include the list of IDs in the order (we need you to let us know the Salesforce field we should map this too please)

Let me know if that all seems correct and we can then get that set up for you this week! 

Apologies again for the delay on my side.

**Comment by ShannonTrust** [comment]
Thanks, @thejoefriel. I'll share with Carol and Jon and let you know their thoughts. I'll also get Chris and Edd involved with regards to Salesforce.

**Comment by thejoefriel** [comment]
Great, thanks @ShannonTrust ! I'll wait to hear back from you

**Comment by ShannonTrust** [comment]
Hey @thejoefriel, I've spoken with Jon and Carol and they are happy with the mock up you provided. Please can you go ahead and start building this into the form. Let me know what you need from us in regards to Salesforce and I'll get Chris and Edd to take a look. Thanks.

**Comment by ShannonTrust** [comment]
Thanks, @thejoefriel 

These are the items that need the prisoner IDs:
SHAN_CALC - Calculator Pack
SHAN_DICT - Dictionary Pack

**Comment by ShannonTrust** [comment]
Hey @thejoefriel, I was wondering if you could give an update on this, please?

**Comment by thejoefriel** [comment]
Hi @ShannonTrust - yes sorry for the delay - it's in progress though and will be finished today.

**Comment by thejoefriel** [comment]
Hi @ShannonTrust - I have the functionality ready to go, but I just want to double check where we will be storing Prison IDs. Here's my suggested approach: https://www.loom.com/share/0ecd7c52463b4f6081e8b59789367e76

Let me know if you're happy with this and I can then deploy this to the main site. 

Thanks!

**Comment by ShannonTrust** [comment]
Hi @thejoefriel, thanks for this. I've checked with Carol and Jon and they are happy with your suggestion. Please go ahead with this.

**Comment by thejoefriel** [comment]
Hi @ShannonTrust this has now been deployed and tested and seems to be working! 

Please note, there was an issue on the description so I had to do a few tests on production These are attributed to the name Joe Friel TESTING so please inform the team so they can delete from Salesforce. 

In the final test (the working one), you will see the description includes the IDs each separated with the + icon . Let me know if anything looks off at all. 

Once you're happy please go ahead and close this issue :)

**Comment by ShannonTrust** [comment]
Thanks so much, @thejoefriel. Carol said it all looks good. Really appreciate your help with this.

**Comment by thejoefriel** [comment]
Great!
