### ISSUE TITLE
Issues with the order resources form

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#119]
### Please select the priority level by adding one of the following labels to this issue?

Priority-2 (High e.g. Core functionality is not working)

### Describe the bug and the expected behaviour.

It's been brought to my attention that we've been having a few issues with orders not coming through properly, people not able submit orders and items being added when people haven't ordered them. Please could you look into this and see what the issue may be?

This is the full email from Carol that outlines all the issues:

Last week
When they place an order on the website they get a confirmation from the website immediately. Guys Marsh  read the confirmation & got in touch , apologising , said she must have made a mistake but thought she had only ordered 2 items. I said no worries , I’d amend .
My next order was a big order & had dictionaries & calculators on so I went back to the Facilitator asking for the Prisoner ID for those items . She then said , she hadn’t ordered all this stuff , only manuals 
I then thought this wasn’t just a coincidence so contacted Swinfen Hall to confirm what she had ordered & again , it was different.

All 3 orders on that day had randomly changed quantities & items on the order.

All orders on the days previously & post were fine

We did have a little blip , similar to this last year . There seems to be an option ( sometimes) to ‘auto-fill’ fields  & If this was chosen it combined their last order ( not stored on the website?? ) with the one they were placing but this isn’t the case with Guys Marsh etc. These were random items never ordered 

The orders recorded on Salesforce include the random items 

This week
A couple of orders have combined their last order with the new order .
Several prisons (approx. 10) have been in touch to say they have tried to place an order but are getting the message “Oops something went wrong”
Yet some orders have gone through , so very hit & miss
I talked Durham through & it submitted on 3rd attempt , but Parc failed again & again.

**Comment by cyberteenie** [comment]
@ShannonTrust - will look at this asap!

**Comment by AbdelhalimOJ** [comment]
@ShannonTrust

Sure, here is the corrected version:

Regarding wrong orders, I saw the form and believe it's quite long, so you might get some input fields autofilled without noticing.

I think we can solve this issue by rethinking the form structure. I suggest that we don't directly submit the form; instead, we first show a summary for the user to review. Then they can confirm their order and submit it.

About people not being able to submit or orders not being collected, I will need to look into Zapier. I am waiting to get access to it.

I understand you are collecting form submissions and pushing them to Salesforce using Zapier. Correct me if I am wrong.

**Comment by ShannonTrust** [comment]
Thanks for looking into this, @AbdelhalimOJ. I've been informed this week that some of our team are looking at alternative formats for the form. My colleague Chris said he will be in touch with Joe about it soon, as I understand Joe knows we've been exploring other options. With that in mind, I'm reluctant to make any big changes to the form right now and I've spoken to the team and they agree to leave it as it is for now - unless you have any quick solutions?

We do use Zapier, but that doesn't seem to be the issue.

**Comment by cyberteenie** [comment]
Hi @ShannonTrust - ok that sounds good, let's just leave it as it is for now and circle back to this when you are ready.
