### ISSUE TITLE
Styling issue with overlapping text on landing page

### ISSUE THREAD

**Issue by cyberteenie** [yalla-coop/shannon-trust-website#121]
### Please select the priority level by adding one of the following labels to this issue?

Priority-2 (High e.g. Core functionality is not working)

### Describe the bug and the expected behaviour.

See screenshot
![Screenshot 2024-05-23 at 11 47 08](https://github.com/yalla-coop/shannon-trust-website/assets/97453274/9d4d0134-ddf8-4395-a6fe-03f280c9f4d6)

**Comment by AbdelhalimOJ** [comment]
@cyberteenie looks like someone fixed it already. I am not seeing that bug anymore. are you still seeing it?

**Comment by cyberteenie** [comment]
@AbdelhalimOJ hmmm strange! It still looks like that for me in one of my Chrome profile windows, but when I open another one it seems to be working, so it must be a local issue! I will try restarting - thanks for looking into it
