### ISSUE TITLE
Resource links now showing - but blank pages show on click through

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#123]
### Please select the priority level by adding one of the following labels to this issue?

Priority-1 (Critical e.g. the website is down, multiple users unable to log into platform)

### Describe the bug and the expected behaviour.

A follow on from the issue raised yesterday - the links are now showing, but when you click on them the page shows blank and isn't pulling up the document

![Website resources blank pages](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/811d5457-9fd1-42e7-a4f7-12fd73a7036b)

### Steps To Reproduce

Visit shannontrust.org.uk/resources
Click on a resource under 'monitoring and evaluation'
Blank screen shows - needs to load document 

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

**Comment by ShannonTrust** [comment]
Sorry, I think this should be priority 2, not 1!

**Comment by cyberteenie** [comment]
Will have a look right away!

**Comment by cyberteenie** [comment]
@ShannonTrust - that should be sorted for you now! Sorry about that.

**Comment by ShannonTrust** [comment]
Thanks, @cyberteenie!
