### ISSUE TITLE
New structure to the 'how you can help' drop down menu

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#124]
### Is your feature / client request related to a problem? Please describe.

There is no current problem, but we have been reviewing the website and we would like to reduce the number of pages shown in the drop down menu under 'how you can help'.

### Describe the solution you'd like

For the new structure we would like to have:
- Donate
- Fundraise
- Leave a gift in your will
- Volunteer
- Work for us

As part of this, we would like to hide 'other ways to give', 'corporate fundraising' and 'challenges and events', as we are now going to link to these from other pages. 

We would also like to delete these pages:
- Information for funders: https://www.shannontrust.org.uk/information-for-funders
- Fundraise your way: https://www.shannontrust.org.uk/fundraise-your-way

**Comment by cyberteenie** [comment]
Sounds good!

**Comment by AbdelhalimOJ** [comment]
@ShannonTrust @cyberteenie This is done now! 😊

**Comment by ShannonTrust** [comment]
Thanks, @AbdelhalimOJ, the drop down menu looks much tidier now! 

With regards to the deleted pages, these can still be found through the search page. Is there a way to make sure these don't show up in the search so people don't end up coming across the 'page not found'?

![Screenshot (316)](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/101ce562-a19f-4498-8fc7-f70d0d7ebbba)
![Screenshot (315)](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/0819cb7c-f8f9-436c-9009-7db6639eb49c)

**Comment by AbdelhalimOJ** [comment]
Hello @ShannonTrust! I've excluded these two pages from the search results. However, it may take some time for this change to take effect since the next scheduled indexing is on Friday. There is a possibility that I can request indexing manually in about two hours from now, so I'll keep an eye on it and see how it goes.

![image](https://github.com/yalla-coop/shannon-trust-website/assets/104467165/0bfd984f-8563-4145-9aba-7237d702407d)

**Comment by AbdelhalimOJ** [comment]
@ShannonTrust Please check now if it is still showing in search results. I tried to search for both pages and they are not showing for me ^^

**Comment by ShannonTrust** [comment]
Hi @AbdelhalimOJ, thanks for sorting this out. They're not showing up in the search for me either. Thank you!
