### ISSUE TITLE
Deleting sections on a number of pages

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#125]
### Is your feature / client request related to a problem? Please describe.

We've got some repeated content across a number of pages, which we've decided isn't necessary. Below are the bits we would like removing on the relevant pages.

### Describe the solution you'd like

**Page: How you can help (https://www.shannontrust.org.uk/how-can-you-help)**
Remove:
- First static quote
- How your donations make a difference section

![Screenshot (304)](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/9944fc9c-a251-4760-97d0-5c8e7a4fac3b)
![Screenshot (305)](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/99038c78-5bf4-4b31-a00e-0240c285f890)

**Page: Donate (https://www.shannontrust.org.uk/donate)**
Remove:
- Other ways to donate section

![Screenshot (306)](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/0767e0f3-405f-475e-b1f2-23b0522daaad)

**Page: Challenges and events (https://www.shannontrust.org.uk/challenges-events)**
Remove: 
- Paying in your fundraising section
- How your donations make a difference section

![Screenshot (307)](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/24440930-ac66-4a1e-b3e8-9136d187a115)
![Screenshot (308)](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/25e718e0-f4fe-47bd-b860-87d7f5791c49)

**Comment by cyberteenie** [comment]
sounds good will do!

**Comment by AbdelhalimOJ** [comment]
@ShannonTrust @cyberteenie This is done now! 😊

**Comment by ShannonTrust** [comment]
Thanks so much, @AbdelhalimOJ
