### ISSUE TITLE
Updates to fundraising page

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#126]
### Is your feature / client request related to a problem? Please describe.

Once a couple of the pages have been deleted, some of the content on the 'fundraise' page will no longer be relevant. 

### Describe the solution you'd like

Under the 'ways to raise funds' section, we currently have 4 boxes linking to other pages. We would now just like 2 boxes - 'challenges and events' and 'corporate fundraising'

We would also like to remove the 'how fundraising makes a difference' section and add in 'paying in your fundraising' which we're removing from the 'challenges and events' page.

![Screenshot (307)](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/cb094148-d899-4545-94a2-172f878a4158)

**Comment by cyberteenie** [comment]
No problem - will do!

**Comment by AbdelhalimOJ** [comment]
@ShannonTrust @cyberteenie This is done now! 😊

**Comment by ShannonTrust** [comment]
Thanks, @AbdelhalimOJ. Looks great!
