### ISSUE TITLE
404 Page Redesign

### ISSUE THREAD

**Issue by AbdelhalimOJ** [yalla-coop/shannon-trust-website#127]
### Describe the solution you'd like

I suggest redesigning the 404 "Page Not Found" page. While it's a small task, it can significantly impact user experience and website effectiveness.

Why It Matters:

1. Enhances User Experience: Guides users back to main content, reducing frustration.
2. Supports Brand Image: Reflects our professionalism and attention to detail.
3. Reduces Bounce Rates: Encourages users to stay on the site with helpful links or humor.
4. SEO Benefits: Handles broken links gracefully, positively impacting search rankings.
5. Provides Analytics: Helps track and understand how often users encounter this page.
6. Redesigning the 404 page can turn a negative experience into a positive one, benefiting both users and our site.

**Example:**

Oops! Page Not Found

We couldn't find the page you were looking for.

Here are some helpful links instead:

[Link 1]
[Link 2]
[Link 3]
[Link 4]

Or try searching our site:
[Search Bar]

Need Help? [Contact Us]

### Screenshots or a link to a Loom Recording

Example of a 404 page from Adobe
![image](https://github.com/yalla-coop/shannon-trust-website/assets/104467165/fe8194ea-4e56-4317-b600-0973cc12c01b)

**Comment by ShannonTrust** [comment]
Thanks for bring this up, @AbdelhalimOJ. It would be great if we could do a redesign so it seems like people are still within our site. Let us know what the next steps are and if you need anything from us.

**Comment by AbdelhalimOJ** [comment]
Hello @ShannonTrust!

Here are the next steps:

1. I will create a design for the page on Figma.
2. I will send it to you for review.
3. Once you approve the design, I will implement it on your website.
4. You will review the final implementation and approve it.
5. We will all be happy 🥳

I estimate that this process will take about 5-10 working days, considering the back-and-forth communication. Let me know if this works for you so I can start designing the page 😊

Thanks!

CC @cyberteenie

**Comment by cyberteenie** [comment]
Hi @ShannonTrust !
I just wanted to clarify that @AbdelhalimOJ estimate of 5-10 working days is a timeline for how long the entire process takes! Regarding SLA time, it's less than a day of work!

**Comment by ShannonTrust** [comment]
Thanks @AbdelhalimOJ and @cyberteenie, that all sounds good to us providing we don't have loads of time still to make up on our SLA

**Comment by cyberteenie** [comment]
@ShannonTrust - we have cleared out the deficit, so will definitely have the time to do it this quarter!

**Comment by AbdelhalimOJ** [comment]
Hi @ShannonTrust considering the SLA time I skipped some steps since the page should be simple and created it directly inside Webflow. you may check how it look like on the staging [here](https://shannon-trust.webflow.io/404)

or just check the attached screenshot:

![Image](https://github.com/yalla-coop/shannon-trust-website/assets/104467165/a2a80a4a-7216-49cb-9c68-a9d39aa94e34)

If there are any specific links you would like to see on that page, please let me know so I can include them.

CC @cyberteenie

**Comment by cyberteenie** [comment]
Hey @AbdelhalimOJ thanks for spinning that up. Looks good to me, but let's see what the ST team thinks!
A couple of things - can we please include the 404 error code somewhere? I know it is not necessary, but it is helpful when trying to help someone that they mention it.
Also, I noticed that when trying to use the search, the text is white. Can we please change that for better legibility? Thank you!!

**Comment by ShannonTrust** [comment]
Hey @AbdelhalimOJ, this looks great, thanks for putting it together. I agree with @cyberteenie comments. I think it would be good to add in a couple of links to prompt people into finding out more about Shannon Trust. Maybe these links can be 'About Shannon Trust' and 'How you can help'.

**Comment by AbdelhalimOJ** [comment]
Thanks @cyberteenie and @ShannonTrust! I've considered your feedback and adjusted the page accordingly. please check: (https://www.shannontrust.org.uk/404)


![Image](https://github.com/yalla-coop/shannon-trust-website/assets/104467165/3561a90c-9a4e-41aa-ab0a-c38069b8c0b2)

**Comment by cyberteenie** [comment]
Looks good! But could we please remove the emoji? There may be some people with lower literacy levels visiting the site and best not to confuse them with any unnecessary punctuation! Otherwise, nice work! Thanks Halim!

**Comment by AbdelhalimOJ** [comment]
@cyberteenie removed it 👍

**Comment by ShannonTrust** [comment]
Looks great. Thanks, @AbdelhalimOJ. Appreciate you doing this so quickly :)
