### ISSUE TITLE
Combing pages

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#128]
### Is your feature / client request related to a problem? Please describe.

We're not posting loads on either the 'news and views' page or 'stories' page. Amy and I have been having some discussions about this and we would like to combine the 2 pages if that is possible please.

https://www.shannontrust.org.uk/news-and-views
https://www.shannontrust.org.uk/stories

### Describe the solution you'd like

We would like the combined page to be 'news and views' and we would like to have 4 tags:
- Learners
- Mentors
- Shannon Trust updates
- Sector news

**Comment by cyberteenie** [comment]
Great, we can certainly do that :) What is of higher priority - this or the 404 page?

**Comment by ShannonTrust** [comment]
Thanks, @cyberteenie. Probably the 404 page as that will impact user experience! There's no rush on this one, just as and when :)

**Comment by AbdelhalimOJ** [comment]
@ShannonTrust 

These are all the categories:

![Image](https://github.com/yalla-coop/shannon-trust-website/assets/104467165/9fe44cb4-8754-46a9-856f-ce27ad29883b)

I understand you need to reduce them to only four:

- Learners
- Mentors
- Shannon Trust updates
- Sector news

- **Community Learners** will be converted to Learners
- **Prison Mentors** will be converted to Mentors, and we will eliminate Community Mentors (there are no stories categorized as Community Mentors anyway, so it won't break anything).
- I am not sure which one from the existing categories should be Shannon Trust Updates.
- **Shannon Trust/Sector News** will be converted to Sector News.

I have already done the page layout and tab names, which you can check on the [staging here](https://shannon-trust.webflow.io/news-and-views).

Once you clarify the different categories, I can apply the changes to the CMS and ensure the tabs display the correct tiles.

**Comment by ShannonTrust** [comment]
Hey @AbdelhalimOJ, thanks for this. It makes sense to change the existing tags. I think it would make sense for the 'news and views' tag to change to Shannon Trust updates, as that's what we currently tag all the articles we upload to the 'news and views' section of our website. Everything else looks good though, thank you!

**Comment by AbdelhalimOJ** [comment]
Hello @ShannonTrust I've implemented the changes: I made the 'Stories' page a draft and kept 'News and Views' with the four tabs, each displaying the specified category. However, I noticed that no cards are appearing under 'Sector News,' so you might need to edit the categorization of some stories.

**Comment by ShannonTrust** [comment]
Thanks, @AbdelhalimOJ - I'm not sure we ever had anything under the 'sector news' tag, but I'll go through and check everything. Could you remove the 'stories' page from the drop down menu, please? Tried to do it myself but couldn't figure out how!

**Comment by AbdelhalimOJ** [comment]
@ShannonTrust Sure I will remove it, I am requesting to take Design control to be able to remove. please accept it.

**Comment by AbdelhalimOJ** [comment]
@ShannonTrust it's done I removed it.

**Comment by ShannonTrust** [comment]
Thank you!
