### ISSUE TITLE
Work for us page update

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#129]
### Is your feature / client request related to a problem? Please describe.

We've moved to using a careers site for our recruitment, so it's no longer necessary to have all the job roles listed on the website (https://www.shannontrust.org.uk/work-for-us). And now we're recruiting more frequently, the roles take up a lot of space on the page.

### Describe the solution you'd like

Could we remove the vacancy collection and instead, under the 'current vacancies' heading, have the sentence 'Join a dedicated team working towards a future where everyone can experience the positive impact of learning. Find the perfect opportunity for you.' With the button 'Visit our careers site', linking to: https://careers.shannontrust.org.uk/paid-vacancies

**Comment by AbdelhalimOJ** [comment]
@ShannonTrust It is ready now for review: https://www.shannontrust.org.uk/work-for-us



![Image](https://github.com/yalla-coop/shannon-trust-website/assets/104467165/887eca4d-15b0-4877-81f8-3ff0fd326686)

**Comment by ShannonTrust** [comment]
Thanks for getting this done so quickly, @AbdelhalimOJ. Looks great :)
