### ISSUE TITLE
Links aren't showing up

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#130]
### Please select the priority level by adding one of the following labels to this issue?

Priority-1 (Critical e.g. the website is down, multiple users unable to log into platform)

### Describe the bug and the expected behaviour.

I've just noticed that all the links we have that are on a white background are now white so you can't see them. Please can this be amended so they are visible.

### Steps To Reproduce

Pages this affects:
https://www.shannontrust.org.uk/contact
https://www.shannontrust.org.uk/other-ways-to-give
https://www.shannontrust.org.uk/fundraise
https://www.shannontrust.org.uk/leave-a-gift-in-your-will
https://www.shannontrust.org.uk/turning-pages

### Screenshots or a link to a Loom Recording

![Screenshot (318)](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/8e0f32af-6255-4a75-b817-3565fbcd4ef5)
![Screenshot (319)](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/5f1ce12f-528f-477f-9cdb-869a2d6b61cc)

**Comment by cyberteenie** [comment]
@ShannonTrust - on it!

**Comment by cyberteenie** [comment]
That should be updated now!

**Comment by ShannonTrust** [comment]
Thanks so much, @cyberteenie!
