### ISSUE TITLE
Part of the title on the homepage isn't left aligned

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#132]
### Please select the priority level by adding one of the following labels to this issue?

Priority-2 (High e.g. Core functionality is not working)

### Describe the bug and the expected behaviour.

I've noticed on the homepage of our site that the blue section of the first heading is no longer left aligned. Would you be able to make sure it's inline with the text above it, please?

### Steps To Reproduce

https://www.shannontrust.org.uk/

### Screenshots or a link to a Loom Recording

![Screenshot (320)](https://github.com/user-attachments/assets/6ad82a17-3128-455b-b6e3-71051ea665db)

### What browsers are you seeing the problem on?

Chrome

**Comment by AbdelhalimOJ** [comment]
Hello @ShannonTrust , that should be fixed now.

**Comment by ShannonTrust** [comment]
Thank you, @AbdelhalimOJ!
