### ISSUE TITLE
Meta pixel set up

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#133]
### Is your feature / client request related to a problem? Please describe.

We're trying to set up Meta pixel but we need some code adding to the website. Would you be able to help us with this if I email over the instructions (they'll come through Facebook)?

**Comment by ShannonTrust** [comment]
Thanks @cyberteenie, they should be coming to you now!

**Comment by AbdelhalimOJ** [comment]
Hello @ShannonTrust I've added the Meta pixel code to the website

**Comment by ShannonTrust** [comment]
Great, thank you @AbdelhalimOJ
