### ISSUE TITLE
Google Tag Manager

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#137]
### Ask your question here.

This came up the other day and you realised we don't have anything set up in Google Tag Manager. I've been setting up some Google Ads and GTM has come up again in relation to tracking conversions. I've been doing research and I can't get my head around what it is or how to set it up. I feel like it's probably something quite important, but are you able to explain to me what the purpose of it is and what we need to do to set it up properly, please?

**Comment by cyberteenie** [comment]
Hey @ShannonTrust!

Good question! It can be a bit confusing to understand the difference between the two tools. [Here's a breakdown ](https://medium.com/@comradeweb/google-tag-manager-vs-google-analytics-what-is-the-difference-1dd6dc1e3e95#:~:text=To%20break%20it%20down%3A%20Google,reports%20on%20these%20tracking%20codes.)that is probably clearer than what I would write!

Installing it is pretty easy, but requires a bit of access to the code, so I recommend signing up for GTM and then sharing your logins for Google Analytics + GTM with us so that we can set it up for you. We can then work with you to ensure that you are tracking whatever it is that is most important for you to track!

Let me know if you have any other questions!

**Comment by ShannonTrust** [comment]
Hi @cyberteenie, thanks for sharing, that makes more sense! Some help setting it up would be really useful. I believe you already have access to our Google Analytics as you set up GA4 for us, and then I did sign up for GTM the other week and gave Abdelhalim access, but I can add anyone else as admin if needed.

**Comment by cyberteenie** [comment]
@ShannonTrust - ok that sounds good. It would be good to jump on a call to discuss what exactly you need tracked as we might be able to do it more simply with Google Analytics. Is there a time next week that would work for you?

**Comment by ShannonTrust** [comment]
Hi @cyberteenie, that would be good. Apart from one meeting at 11.30am, I'm free most of Wednesday next week if there's a time you're available?

**Comment by cyberteenie** [comment]
@ShannonTrust - great! I will send around a meeting invite for Wednesday at 2:30 UK time. Let me know if that works for you.

**Comment by AbdelhalimOJ** [comment]
Hi @ShannonTrust for our technical research about GTM setup and conversion linking we would need you to invite us to your Google Ads account (abdelhalim@yallacooperative.com)

**Comment by ShannonTrust** [comment]
Hi @AbdelhalimOJ, I've tried adding you to Google Ads, but it says the domain can't be used. Do you have a gmail account I can use instead?

**Comment by AbdelhalimOJ** [comment]
Hi @ShannonTrust , Yes I will need access to Google Ads and GCP. you can invite abdelhalim.aljaml@gmail.com

**Comment by ShannonTrust** [comment]
@AbdelhalimOJ I've added you to our Google Ads account. We don't have GCP and it needs us to put in the credit card details to set it up. Our current card is about to expire and I'm waiting for the updated details. Do we definitely need GCP? If so, it might need to wait until I get the new card details.

**Comment by AbdelhalimOJ** [comment]
Hi @ShannonTrust I am exploring the normal conversion linking between GTM, Google Ads and Meta Pixel without the need for Server-Side (requires GCP) .. Can you please upgrade my permission on your GTM account?

![Image](https://github.com/user-attachments/assets/a06e60c1-1aaa-4115-9730-0ebbcad48e58)

**Comment by ShannonTrust** [comment]
Hi @AbdelhalimOJ, apologies, I thought I had given you full access. I have changed the permissions now.

**Comment by AbdelhalimOJ** [comment]
Hi @ShannonTrust,

I reviewed your Google Ads account and noticed you have only one active campaign directing traffic to your [volunteer page](https://www.shannontrust.org.uk/volunteer), with some conversions recorded.

Could you share the main goal of this campaign? If you want visitors to check the [Volunteer roles](https://careers.shannontrust.org.uk/volunteer-roles) page and apply for a role, the conversion should be set up to track users who visit the initial page, navigate to volunteer roles, click on a specific role, go to the application form, and then submit it.

This way, a conversion indicates that an application has been submitted, allowing Google Ads to optimize your campaign to attract more users who are likely to complete this journey.

I know this is a lot to take in, so we might want to discuss it in a meeting. I’m not an expert in setting this up, but the current conversion is quite general and not specific to this campaign. As shown in the screenshot below, when campaigns are linked to the right conversion events, you can expect more accurate results and better campaign performance:

![image](https://github.com/user-attachments/assets/f52d7f62-c071-4e9e-bce1-11e45d5cf35b)

I’ve already installed GTM on the website, and I see there are conversion events linked to GA4 in Google Ads.

Looking forward to your thoughts!

**Comment by ShannonTrust** [comment]
Hi @AbdelhalimOJ, I think in the long term we probably would want to track when people apply to the roles, but because we don't have loads of people apply anyway, I think to start with it would be good just to track when people click to find out more about the roles through this link: https://careers.shannontrust.org.uk/volunteer-roles

**Comment by AbdelhalimOJ** [comment]
Hi @ShannonTrust 

To wrap up our conversation, I suggest setting up a meeting with your marketing team to exchange ideas and explore potential collaboration. Since GTM is installed on the website, do they need us to handle anything specific on it?

CC @cyberteenie

**Comment by ShannonTrust** [comment]
Thanks, @AbdelhalimOJ. Now that GTM is installed, is it easier for us to set up conversions ourselves? Or will any other code need to be added?

**Comment by AbdelhalimOJ** [comment]
Yes @ShannonTrust  it is easy to set it up .. you may need us to add a script rarely in special cases if you wanted to create a custom event for example.

**Comment by ShannonTrust** [comment]
Thanks @AbdelhalimOJ. Let me look into it a bit more so I can see how to set up the conversions and I'll let you know if we need any further support.

**Comment by cyberteenie** [comment]
Hey @ShannonTrust - just wanted to see if we were okay to close this issue or if more support was needed?

**Comment by ShannonTrust** [comment]
Hi @cyberteenie, I've been on leave so I'll be looking into this in more detail over the next couple of weeks. If I don't need any support, I'll close the issue. Thanks.
