### ISSUE TITLE
Changes to order resource form

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#139]
### Is your feature / client request related to a problem? Please describe.

We're going to be moving our order resource form over to Salesforce soon, so the current form on the website will no longer be needed. It also means we should be able to get rid of Zapier. We're looking to make this live sometime in October - date still to be confirmed. 

The order form is currently a hidden page on the website, so we will need to remove this page and redirect the link to the new page in case people have it saved on their desktop.

**Comment by AbdelhalimOJ** [comment]
Hey @ShannonTrust This can be done easily. Once the link to the external page is ready, just let us know, and we'll set up the redirect from www.shannontrust.org.uk/order-resources to the new URL.

**Comment by ShannonTrust** [comment]
Hi @AbdelhalimOJ, we would like to switch over to the new order form on Friday 18 October - preferably in the morning. Could you redirect the link here on this date, please: https://shannontrust.my.site.com/

**Comment by AbdelhalimOJ** [comment]
Hi @ShannonTrust sure will do that

**Comment by AbdelhalimOJ** [comment]
Hi @ShannonTrust I unpublished the resources page and created the redirect to [](https://shannontrust.my.site.com). however, it is showing this error message:
![Image](https://github.com/user-attachments/assets/d55362eb-f2eb-4e4e-9043-2272a3101608)

**Comment by ShannonTrust** [comment]
Thanks @AbdelhalimOJ. We think it's because they're changing things over in the background, so hopefully it will be live soon. But thank you for the redirecting the page, I think that will be everything we need you to do.
