### ISSUE TITLE
Cookiebot detecting over 10,000 subpages

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#140]
### Please select the priority level by adding one of the following labels to this issue?

Priority-3 (Normal e.g. Functionality is not working for a subset of users)

### Describe the bug and the expected behaviour.

Further to an email I sent Kristian about an increase in what we're paying for Cookiebot, I contacted their support team to understand why we're being charged more when we definitely don't have more than 3,500 subpages as their subscription page outline. They got back to me and said they detected over 10,000 pages - all of which come up as the news and views pages, but not the actual stories. Would you be able to investigate this further for us please as I'm really unsure why these pages are showing up in the scan when they're not even real pages.

### Screenshots or a link to a Loom Recording

Response from Cookiebot and the file they attached to show the pages detected 

[urlindex-2071909.csv](https://github.com/user-attachments/files/17162693/urlindex-2071909.csv)
[[Cookiebot Support] Re_ Increase in subscription cost.pdf](https://github.com/user-attachments/files/17162696/Cookiebot.Support.Re_.Increase.in.subscription.cost.pdf)

**Comment by cyberteenie** [comment]
Thanks for looking into that Megan! We will look into it.

**Comment by cyberteenie** [comment]
@ShannonTrust - can you please forward the login verifcation email that was sent to media@shannontrust to abdelhalim@yallacooperative.com so that he can look into the Cookiebot issue a bit deeper please?

**Comment by ShannonTrust** [comment]
Hey @cyberteenie, we only had an email to activate the account. I clicked on the link and it says our account has now been verified, but we already have an account, so not sure why this was needed.

**Comment by AbdelhalimOJ** [comment]
Hi @ShannonTrust The pages identified by the Cookiebot scanner are not distinct; they are all variations of the same page, differentiated only by a query parameter that indicates the page number due to the paginated news collection. The solution is to redesign the news page to load all news items at once instead of four at a time.

If you agree with this approach, please let us know, and we can begin implementing the changes on the news page.

**Comment by ShannonTrust** [comment]
Hi @AbdelhalimOJ, thanks for looking into this. Here is the report: 
[Cookie scan report October 2024.pdf](https://github.com/user-attachments/files/17221569/Cookie.scan.report.October.2024.pdf)

I can't see where the pages are shown, but the compliance issue is coming up again. 

I'm happy for you to go ahead with the pagination edits if you think that's best.

**Comment by AbdelhalimOJ** [comment]
Hi @ShannonTrust I'll look into the compliance issue. I've disabled pagination and applied another solution. You won't notice any changes, it's just a different implementation. This should stop the subpages from being generated.

**Comment by AbdelhalimOJ** [comment]
They say "Check the attached report to find out which scripts are loaded before consent" in the PDF file, is there any other report attached to this?

**Comment by ShannonTrust** [comment]
Thanks, @AbdelhalimOJ. Sorry, I thought you would have been able to click the link in the file in the PDF. I can't attach it separately as it's a HTML document. But if you go into the Cookiebot account and click into the reports tab, it's the first one that comes up.

**Comment by AbdelhalimOJ** [comment]
Thanks @ShannonTrust I checked all the cookies that weren't blocked until the user accepted them and made the necessary fixes on the website. However, there's still one script loading before consent, which is related to fonts. We're using a font from Adobe called "Aller," and I need to know if we're using Adobe Fonts from your account or ours.

If we are using your Adobe account, could you please check if you can get me the Adobe Fonts API Key? This will help me fix the issue with the fonts script.

**Comment by ShannonTrust** [comment]
Hi @AbdelhalimOJ, thanks for making the changes. Looking in our Adobe account, we don't have any API tokens. When we rebranded, we worked with a designer who sent us the fonts, so I'm assuming they're likely from his account. Will it still work if I set up a new API token, or will it need to be through the designer?

**Comment by AbdelhalimOJ** [comment]
if possible to get it through the designer it is preferable. @ShannonTrust

**Comment by ShannonTrust** [comment]
@AbdelhalimOJ OK, leave it with me and I'll get back to you when I know more.

**Comment by ShannonTrust** [comment]
Hi @AbdelhalimOJ, this is the response I had from the designer:

_When I finished the rebrand with you guys in 2021 I handed over the open artwork and brand guidelines to your developers. 'Aller' was being used as an Adobe Typekit font my end, but wouldn't have been included in the open artwork as you can't transfer fonts that are being streamed in via the creative cloud. At that point my involvement came to an end and the original developers would have had to source a version of 'Aller' in order to populate the new website. So I don't think you'd have had access to anything from my Adobe cloud account. 

There might be an issue with the font API they've originally used, has your website hosting platform been updated recently? Sometimes newer versions of the CMS you're using can cause some issues with older fonts/APIs if they're not kept up to date. 

The only other way around I can think of would be to purchase a copy of the desktop license from the original source: https://www.daltonmaag.com/font-library/aller.html#retail_

Is it possible that we're using the font from your account?

**Comment by AbdelhalimOJ** [comment]
Hi @ShannonTrust thanks for getting back to me. I am checking with the team if we used the Adobe API key from our account.

**Comment by AbdelhalimOJ** [comment]
**Latest Update**
re subpages I requested generation of a new scan report to see if disabling pagination solved the issue of 10,000 subpages or not.

**Comment by ShannonTrust** [comment]
Thanks for the update @AbdelhalimOJ. Is there anything else I need to do? 

We've had another report come through and it looks like the compliance issue is sorted.

**Comment by AbdelhalimOJ** [comment]
Hi @ShannonTrust ! Yes I just saw it is now 121 subpages only ^^

![image](https://github.com/user-attachments/assets/91c484cd-11cd-472f-a5fa-00564a8443d1)

Nothing else to do. Thanks and feel free to close this issue.

**Comment by ShannonTrust** [comment]
Super, thanks so much @AbdelhalimOJ :)
