### ISSUE TITLE
Buttons are blank and not clickable

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#141]
### Please select the priority level by adding one of the following labels to this issue?

Priority-2 (High e.g. Core functionality is not working)

### Describe the bug and the expected behaviour.

We've noticed that some of the group buttons on a few of the pages on the website are either blank and not clickable, or they've all gone black. I've looked in the designer side of Webflow, but can't see how to change them. Can you review, please?

### Steps To Reproduce

Pages this is showing up on:

https://www.shannontrust.org.uk/about-us
https://www.shannontrust.org.uk/impact
https://www.shannontrust.org.uk/how-can-you-help
https://www.shannontrust.org.uk/challenges-events

### Screenshots or a link to a Loom Recording

![Screenshot (332)](https://github.com/user-attachments/assets/d64b6eb8-9758-4e85-a2dd-2e022596f5d8)
![Screenshot (333)](https://github.com/user-attachments/assets/484e01c9-e59b-4ad7-b5c1-7bfa0582e2cd)
![Screenshot (334)](https://github.com/user-attachments/assets/9b07af16-e181-4067-9bda-88cf2d52ab3f)
![Screenshot (335)](https://github.com/user-attachments/assets/5903f1e4-c88f-48e0-b103-2777c08264f8)

**Comment by AbdelhalimOJ** [comment]
will fix it now ^^

**Comment by AbdelhalimOJ** [comment]
Hi @ShannonTrust it is now fixed! please check again

**Comment by ShannonTrust** [comment]
Thanks for sorting it out so quickly, @AbdelhalimOJ. All back to normal!
