### ISSUE TITLE
Adding funder logos to the website

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#142]
### Ask your question here.

I was asked about what the possibilities would be to adding some of our funder logos onto the website. I don't want them crowding the footer of our website, so I wanted to ask you what options we might have? Would we be able to have a carousel somewhere on one of the pages, where it scrolls along on its own? I'll look for some examples of what we might want and see if we can do them within Webflow.

**Comment by AbdelhalimOJ** [comment]
Hi @ShannonTrust , How about placing this just above the footer on the About Us page? Or, if you'd prefer, we could integrate it into the footer itself and control its visibility on specific pages. Let me know what you think! ^^

![Image](https://github.com/user-attachments/assets/6e6c52e6-b07d-4952-8f28-e99cfe85d651)

**Comment by AbdelhalimOJ** [comment]
Hi @ShannonTrust , I estimate it will take about an hour to upload the logos and build this component. If that works for you, please share the logos you'd like to include in the slider.

**Comment by ShannonTrust** [comment]
Hi @AbdelhalimOJ, that's great, thanks for letting me know. We would like the logos on the 'About us' page like you suggested, above the footer. 

Here are all the logos I've received. I'm not sure if they're high enough quality, so let me know if not and I'll go back to the team.

![The goldsmiths company](https://github.com/user-attachments/assets/eb65ad82-d69a-4bc3-9f37-149cf551e4aa)
![Adrian Swire Charitable Trust](https://github.com/user-attachments/assets/45f7a14f-69c4-433b-81e9-408aff9aa875)
![Emmanuel Kaye Foundation](https://github.com/user-attachments/assets/5ab8d032-7284-49b7-a4b5-604362567407)
![Garfield Weston](https://github.com/user-attachments/assets/500177b6-1ecd-4bd8-a04d-725e0709769d)
![J HRausing](https://github.com/user-attachments/assets/378ce1f7-56fe-4a87-b464-9e0a36b8e0d7)
![Porticus](https://github.com/user-attachments/assets/0aabddc4-4d5f-4d05-83c6-2b1e8b9edd97)
![The Considered Ask](https://github.com/user-attachments/assets/afbc9b90-8a9e-4ccf-a374-ec31a1de3edf)

**Comment by AbdelhalimOJ** [comment]
Hi @ShannonTrust I have added the section above the footer in the about us page and you can see it on the staging [here](https://shannon-trust.webflow.io/about-us)

in terms of logos quality I think some of them aren't looking good .. you can upload another versions for us to add or simply replace the logos yourself within the CMS.
![Image](https://github.com/user-attachments/assets/88b9dfbf-788d-4b1b-ae41-9aeaf8171814)

**Comment by ShannonTrust** [comment]
Hi @AbdelhalimOJ, thanks for this. Sorry for the delay, I was on annual leave last week. Are we able to make some of the logos smaller, please? For example, The Considered Ask and Garfield Weston, that way they're a similar size to the others?

**Comment by redahaq** [comment]
Hi @ShannonTrust, yes of course -we've adjusted those larger logos as requested. Please see [here](https://shannon-trust.webflow.io/about-us). Let us know if there any further changes required and we'll be happy to make them.

**Comment by ShannonTrust** [comment]
Thanks, @redahaq. That's great.
