### ISSUE TITLE
Changes to challenges and events page

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#144]
### Is your feature / client request related to a problem? Please describe.

We have signed up to a new fundraising platform and we would like to add a new section onto the challenges and events page to showcase this.

### Describe the solution you'd like

https://www.shannontrust.org.uk/challenges-events

Underneath the 'get in touch' banner, we would like a new section titled 'Take on a challenge'. Here we would like 3 boxes to include 5K events, 10K events and half marathon events - a similar idea to what Book Trust have on this page: https://www.booktrust.org.uk/support-us/challenge-event. 

Links for the 3 boxes:
- 5k events: runforcharity.com/shannon-trust/5km-events 
- 10k events: runforcharity.com/shannon-trust/10k-events
- Half marathons: runforcharity.com/shannon-trust/half-marathons

Underneath the 3 boxes, we would like a drop down menu for 'Find an event in your area' and we will have a list of links to different regions. 

If you're not sure about anything, or you need anything else, please let me know. 

If possible, please can this be complete by 2 January 2025? Amy and I will be away from Friday 20 December until 2 January.

**Comment by cyberteenie** [comment]
HI @ShannonTrust ! We can get this done by then. I will keep you updated!

**Comment by redahaq** [comment]
Brilliant, thank you. I've added the links - https://shannon-trust.webflow.io/challenges-events. Are you happy for me to publish to production and close the issue?

**Comment by ShannonTrust** [comment]
Thanks, @redahaq. Nothing is showing in the dropdown when I click on it. I can click on the 3 boxes, which open the links, but not the drop down menu.

**Comment by redahaq** [comment]
Hi @ShannonTrust, would you mind testing again please? If it's still not working please can you take a video and share the details of the browser/ device. Thank you!

**Comment by ShannonTrust** [comment]
Hi @redahaq, it seems to be working now. Happy for you to publish and close the issue. Thank you.
