### ISSUE TITLE
Footer (incl. Mailchimp set up)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/shannon-trust-website#15]
__Further info__

I've included Salesforce x Zapier set up in this so we can have the footer completely done 

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

**Footer creation**
- [x] Create footer https://www.figma.com/file/vC6iqpWqeTJSPkM0Lswcfp/Shannon-Trust---Website?node-id=214%3A157
- [x] Set up social media links (always opens on a new tab) 
    - [x] Twitter - https://twitter.com/Shannon_Trust
    - [x] Facebook - https://www.facebook.com/ShannonTrustCharity/
    - [x] Instagram - https://www.instagram.com/shannontrustcharity/
    - [x] YouTube - https://www.youtube.com/channel/UCFHn0VZ3CQAWnltjSguJ_Ig
    - [x] LinkedIn - https://www.linkedin.com/company/shannon-trust
- [x] Add dummy link for Privacy policy for now - ST need to supply

**Newsletter set up**
- [x] Reach out to megan@shannontrust.org.uk to get the login details for Mailchimp / be added as a member and confirm where to send the data
- [x] Set up integration with webflow to send the email to agreed place on submission

---

### Needed from Design 

Hey @bethanyios 

- [ ] Get the Charity number and update the wireframe
- [x] Can you link the contact us and work for us in figma please (I'm assuming they are website pages?)

**Comment by RamyAlshurafa** [comment]
closing this as client can change it via editor anytime
