### ISSUE TITLE
How can you help

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/shannon-trust-website#16]
---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [x] Create page https://www.figma.com/file/vC6iqpWqeTJSPkM0Lswcfp/Shannon-Trust---Website?node-id=288%3A1826
- [ ] CMS collections
    - [ ] Carousel (limits - Min = 3 / Max = 5)
- [x] Please refer to text limits in Figma comments
- [ ] Please follow prototype links in Figma
- [x] Immediate benefits for learners - this is static with the 4 benefits, but the text and icon can be changed 
- [x] How your money makes a difference - same as above

**Comment by RamyAlshurafa** [comment]
As Agreed with @jema28 and referring to CMS session it should not be carousel, it pull the data from CMS put show the one item
