### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/shannon-trust-website#18]
---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [x] Create page https://www.figma.com/file/vC6iqpWqeTJSPkM0Lswcfp/Shannon-Trust---Website?node-id=214%3A7
- [x] Please refer to text limits in Figma comments
- [x] Please follow prototype links in Figma
- [x] Clicking any email opens the default email software of the user
- [x] Clicking any phone number (if on mobile) triggers the call 
- [x] Contact will send the form data as an email to communications@shannontrust.org.uk  
- [x] On success show standard form submission success message https://www.figma.com/file/vC6iqpWqeTJSPkM0Lswcfp/Shannon-Trust---Website?node-id=824%3A4899
- [x] Clicking each name (e.g. Caroline Ludbrook) would be a mailto link so the email service of the user would appear 

---

- [x] Megan to add the email addresses here

**Comment by meganlouisejackson** [comment]
Email address for regional managers:
James Argent: james@shannontrust.org.uk
Karen Ryan: karen@shannontrust.org.uk
Milly Connelly: milly@shannontrust.org.uk
Verity McLelland: verity@shannontrust.org.uk
Scott Haines: scott@shannontrust.org.uk

This is slightly different to the list that's in the current copy, but has been updated in the Google doc.

**Comment by RamyAlshurafa** [comment]
https://shannon-trust-website.webflow.io/contact
