### ISSUE TITLE
Blog Post - News & Views

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/shannon-trust-website#19]
__Further info__

This is part of the News & Views CMS collection

Might be useful to create at same time as #9 since a lot of the core functionality if the same (except there's no tags)

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [ ] Create this page in line with wireframes https://www.figma.com/file/vC6iqpWqeTJSPkM0Lswcfp/Shannon-Trust---Website?node-id=571%3A3309
- [ ] Please refer to text limits in Figma comments
- [ ] Please follow prototype links in Figma
    - [ ] Two links at the bottom of every post is always Stories and How you can help

**Required Fields**
- [ ] Title
- [ ] Author name
- [ ] Publication date (default to today if no date put in)
- [ ] Text (rich text editor)

**Optional Fields**
- [ ] Image - if not provided fall back to placeholder https://www.figma.com/file/vC6iqpWqeTJSPkM0Lswcfp/Shannon-Trust---Website?node-id=956%3A7384
    - [ ] Minimum image size = 1440 x 752px (we need to ensure big images are added to ensure high quality for the top)
- [ ] Audio file / link (depending on what is best to make this work). Only one audio can be added
- [ ] Video file / link (depending on what is best to make this work). Only one video can be added 
- [ ] Featured - this will always make it appear at the top of the News & Views section

**Comment by thejoefriel** [comment]
Hey @RamyAlshurafa same point here about quotes as in #9

**Comment by RamyAlshurafa** [comment]
> Hey @RamyAlshurafa same point here about quotes as in #9

yeah replied there,

also closing this as we agreed to make them in one collection with stories 
https://github.com/yalla-coop/shannon-trust-website/issues/10
