### ISSUE TITLE
News & Views

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/shannon-trust-website#20]
__Related issue(s)__

The blog post that makes up the collection is here: #19  

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [x] Create Stories page https://www.figma.com/file/vC6iqpWqeTJSPkM0Lswcfp/Shannon-Trust---Website?node-id=214%3A471
- [x] CMS collections: 
    - [x] Collection of all 'news & views' posts #9 
    - [x] Get feed of 4 posts then load 4 more on click
    - [x] Always list in order of most recently published (but prioritise featured ones)
- [x] Please refer to text limits in Figma comments
- [x] Please follow prototype links in Figma
- [x] Add social feed embeds
    - [x] Each is just an iframe (put it in custom code)
    - [x] Twitter: can get the embed iframe code here: https://publish.twitter.com/?query=https%3A%2F%2Ftwitter.com%2FShannon_Trust&widget=Timeline
    - [x] Facebook: can get the embed iframe code here: https://developers.facebook.com/docs/plugins/page-plugin/

**Comment by RamyAlshurafa** [comment]
https://shannon-trust-website.webflow.io/news-and-views

Note: social embedded for facebook is not responsive so I had to put the widt to 370px
