### ISSUE TITLE
Donate (incl. Enthuse set up)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/shannon-trust-website#27]
__Further info__

This will embed the Enthuse form so this will be the point to link up with Shannon Trust to get the Enthuse details and ensure everything is set up correctly 

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [x] Create page https://www.figma.com/file/vC6iqpWqeTJSPkM0Lswcfp/Shannon-Trust---Website?node-id=214%3A623
- [x] Contact megan@shannontrust.org.uk to get the Enthuse account details at this point so we can get it working in the app 
- [x] When clicking "Read Theo's story" scroll down to story section further down the page
- [x] Please refer to text limits in Figma comments
- [x] Please follow prototype links in Figma

**Comment by thejoefriel** [comment]
Hey @RamyAlshurafa this is for donately, but the lesson on how to embed an iframe would be same I think: https://donately.zendesk.com/hc/en-us/articles/360034303893

**Comment by RamyAlshurafa** [comment]
Hey @thejoefriel 
>  When clicking "Read Theo's story" scroll down to story section further down the page

Where is that "Read Theo's story" link please? I cant find it

**Comment by thejoefriel** [comment]
Oh sorry @RamyAlshurafa that CTA actually was a late change to the wireframes so that acceptance criteria is not applicable anymore

**Comment by RamyAlshurafa** [comment]
Closing this as we agreed to not embed Enthuse in iFrame and use external links instead
