### ISSUE TITLE
Work for us

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/shannon-trust-website#30]
---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [x] Create page https://www.figma.com/file/vC6iqpWqeTJSPkM0Lswcfp/Shannon-Trust---Website?node-id=214%3A614
- [x] CMS collections
    - [x] Current vacancies, fields include
        - [x] Title
        - [x] Description
        - [x] Link to find out more (opens new tab)
        - [x] Closing date (this would text so you could put in what you wanted)
- [x] Please refer to text limits in Figma comments
- [x] Please follow prototype links in Figma

---

### Needed from design 

Hey @bethanyios 
- [ ] Can you confirm where the vacancy posts link to ? I can't see it prototyped but I also can't see what you click to apply?

**Comment by RamyAlshurafa** [comment]
https://shannon-trust-website.webflow.io/work-for-us
