### ISSUE TITLE
Challenges & Events

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/shannon-trust-website#36]
---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [x] Create page https://www.figma.com/file/vC6iqpWqeTJSPkM0Lswcfp/Shannon-Trust---Website?node-id=214%3A821
- [x] CMS collections
    - [x] Carousel (limits - Min = 3 / Max = 5)
    - [x] Fundraising resources 
- [x] Please refer to text limits in Figma comments
- [x] Please follow prototype links in Figma
- [x] How fundraising makes a difference - this is static with the 3 benefits, but the text can be changed

**Comment by RamyAlshurafa** [comment]
Hey @bethanyios @jema28 
can you check this page as I don't see any difference in the content between it and Fundraise your way page, except of first section

**Comment by jema28** [comment]
Hey @RamyAlshurafa, yes it's very similar, just the list and the hero links at the end are different. And maybe different quotes also
