### ISSUE TITLE
Create style guide

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/shannon-trust-website#4]
### Further info
This is to set up all the core styling for the webflow project

---

### Acceptance criteria

- [x] Colors
- [x] Typography
- [ ] Spacings
- [x] Shadows

---

### To be added by design 

Hey @bethanyios can you upload here please:
- [x] Fonts

**Comment by bethanyios** [comment]
Design System https://www.figma.com/file/vC6iqpWqeTJSPkM0Lswcfp/Shannon-Trust---Website?node-id=788%3A5438

**Comment by bethanyios** [comment]
Here are the fonts https://drive.google.com/drive/folders/1qzW2y1MayamFf1WaUVdEOCk-d5jHbQA-?usp=sharing
