### ISSUE TITLE
User Acceptance Testing 🐛 

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/shannon-trust-website#44]
This issue is to cover the process for Bug Testing for the latest earn sprint. 

**What is bug testing?**
Bug testing is a very important phase to ensure the app is working as discussed, and to test all the various flows to ensure any potential problems can be fixed before final deployment. 

**The process**
This is an outline on how to carry out bug testing
https://www.notion.so/yallacooperative/Bug-Testing-abf02f7b154240b19cf35802284508d4

**Journeys**
Remember to refer either to the user journeys in whimsical or the figma wireframes for a clear outline of all the pages and flows to check

**Here is the table where all bugs should be listed**
https://www.notion.so/yallacooperative/f4eb017cb51a475f96916a8d84875b26?v=ce0d8320591843e18639f2c70ca5b492

**App can be tested here**
Link to staging version of the app to be provided here (please remember if inactive for 30 minutes the app will take 20 seconds to load)
https://shannon-trust.webflow.io/

**Dates for bug testing**
TBC

**Comment by thejoefriel** [comment]
**Update**
Hey @RamyAlshurafa to update you, Shannon Trust have gone through all the bugs you said were fixed. There are a couple with some comments from them along with some new ones. 

Can you please go through and let me know here once you've done another full sweep please? Any ones where you feel they are not a bug or we need something from them, can you please add as a comment? I think that'll be easier to track since they've already written in the notes column quite a bit

**Comment by RamyAlshurafa** [comment]
Hey @thejoefriel 
all the bugs are fixed except for one I added a comment for Meggan, and also fixed a couple of "backlog" and "copy" ones
