### ISSUE TITLE
Final Settings for Deployment

### ISSUE THREAD

**Issue by jema28** [yalla-coop/shannon-trust-website#46]
- [x]  Remove 'Powered by Webflow' from settings
- [x]  Make sure SEO metadata has been set up
- [x]  Add favicon to the website
- [x]  Disable Webflow subdomain indexing (so Google doesn't search index the staged domain we already created) under SEO

**Comment by thejoefriel** [comment]
Hey @RamyAlshurafa have these things been done?

**Comment by RamyAlshurafa** [comment]
> Hey @RamyAlshurafa have these things been done?

Yeah @thejoefriel they have been done
