### ISSUE TITLE
Create Resources Page

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/shannon-trust-website#47]
**Summary**
We need to create an unlisted page (i.e. it's not linked to anywhere else in the website) where users can download a bunch of different resources

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [x] Create this page https://www.figma.com/file/vC6iqpWqeTJSPkM0Lswcfp/Shannon-Trust---Website?node-id=1465%3A10110
- [x] Confirmation of list of resources
    - **Monitoring and Evaluation**
        - Activity register
        - Activity register user guide
        - Learner log sheet
        - Monitoring form
        - Progress profile
    - **Practice guides**
        - Practice guide for volunteers
        - Practice guide for mentors
        - Practice guide for prison staff
    - **Mentor training**
       - How to be a mentor self study booklet
       - Welcome session and associated docs (mentor compact, mentor role description, person specification and current activity overview for new mentors).
       - Core session and associated docs (decoding text, muddled word text, training feedback forms
       - Bolt on sessions and associated docs.
       - In cell activity packs
    - **General**
        - Prison action plan
        - Prison action plan guidance document
        - Mentor recruitment advert
        - Backwards prison app
        - Mentor coordinator role description
   - **Volunteers documents**
       - Expense form
       - Bank details form
       - Accident report form
       - Meeting checklist
       - Mentor meeting template
- [x] We don't have the resources for now, so just use one dummy example of each file type. ST can then replace with the correct version 
- [x] It would be a CMS collection where they can:
    - Upload 1 x file (PDF, xlsx, docx, pptx) max 10mb OR provide a link to the file (for zip file types - we'd suggest using something like Dropbox, Sharepoint, Google Drive)
    - Select the category (e.g. Monitoring and Evaluation)
    - Give it a written title (e.g. Activity register)
    - This approach will let them add / remove / edit items from each section (but please note, you wouldn't be able to create new sections)
- [x] No 'load more', we'd just list all of them on the page so if they keep adding more, more will be listed and the page will become longer

**Comment by RamyAlshurafa** [comment]
Done!
https://shannon-trust.webflow.io/resources
