### ISSUE TITLE
Manage Domain

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/shannon-trust-website#49]
Hi @RamyAlshurafa we need to liaise with Phil on arranging the DNS on their hosting provider to point to the new site. Can you write down here please as a comment what we need to do to point the website at Webflow? I'll then look to either share with Phil or set up a meeting to talk through

**Comment by RamyAlshurafa** [comment]
Hey @thejoefriel 
we need a `CNAME`, and 2 `A`s records from the hosting provider,

for more details you can find how to get them from here https://www.youtube.com/watch?v=MmVDd3Ovho8&t=135s

**Comment by thejoefriel** [comment]
Hey @RamyAlshurafa it looks like we need to send him the records. Can you get them from webflow and paste them here please?

**Comment by RamyAlshurafa** [comment]
Hey @thejoefriel 
no, the records are from domain provider, not webflow, so they have to send the records so I can add them into webflow

**Comment by RamyAlshurafa** [comment]
Hey @thejoefriel 
yeah we need to know the domain they want to use, so I can add it into webflow to create the records

**Comment by thejoefriel** [comment]
The domain @RamyAlshurafa is shannontrust.org.uk
