### ISSUE TITLE
Ensure questions are up to date

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/shannon-trust-website#51]
Hey @RamyAlshurafa Shannon Trust have sent a final version of the  the volunteer application questions. Do you mind going through the forms and making sure they are consistent please? 

To confirm the current form order would the same (eligibility questions aren't to go at the bottom, they are just there at the bottom in the document as that's the one question that changes per role)

Thanks! 

https://docs.google.com/document/d/10i80B-J0RKpHGHf5NRu-xUPp9j4l7QTB/edit?usp=sharing&ouid=114487763822736370607&rtpof=true&sd=true

**Comment by RamyAlshurafa** [comment]
Hey @thejoefriel 
Here are the list of questions have been deleted in Volunteer form:
- What is your name?
- How many hours per month could you offer the Shannon Trust?
- If yes to either of the above questions, please provide details

shall I proceed and delete them?

**Comment by thejoefriel** [comment]
Hey @RamyAlshurafa just to confirm what was in emails to ensure we have it documented here, keep the name, but delete the other two please
