### ISSUE TITLE
Add content editors

### ISSUE THREAD

**Issue by jema28** [yalla-coop/shannon-trust-website#52]
Add Carrie, Chris and Carol as editors:
Carrie Petitt: carriepetitt@gmail.com
Carol: carol@shannontrust.org.uk
Chris Morgan: chris@shannontrust.org.uk

**Comment by jema28** [comment]
Hey @RamyAlshurafa can you please sent invites to the above email addresses?

**Comment by RamyAlshurafa** [comment]
Done @jema28

**Comment by jema28** [comment]
Thanks @RamyAlshurafa
