### ISSUE TITLE
Add address field to resource form

### ISSUE THREAD

**Issue by cyberteenie** [yalla-coop/shannon-trust-website#57]
**Is your feature / client request related to a problem? Please describe.**
Client requested the address field is added to resource form

**Describe the solution you'd like**
Address field is included in resource form

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by cyberteenie** [comment]
@RamyAlshurafa - just wanted to check - was this issue ever picked up?

**Comment by thejoefriel** [comment]
Hey @RamyAlshurafa are you able to add the address field in the Shannon Trust form please? I can then update it on the Zapier side.

**Comment by RamyAlshurafa** [comment]
Hey @thejoefriel 
these fields are already there
fields are:
- Address line 1
- Address line 2
- City
- Postcode

**Comment by cyberteenie** [comment]
@thejoefriel - ok! I have just sent Chris an email asking for an update on this. Thanks!

**Comment by cyberteenie** [comment]
@thejoefriel just wanted to update you that Chris says that he needs to do a bit of work on Salesforce before this can be implemented and will get back to us as soon as he can. I will let him know that we need to know which Salesforce table that they need to get into.

**Comment by thejoefriel** [comment]
Hey @cyberteenie - can this be closed?

**Comment by cyberteenie** [comment]
@thejoefriel - no, it is still on hold until Chris gets back to us. He had deprioritised it as it needed some work in Salesforce that he was unable to do at the time.

**Comment by ShannonTrust** [comment]
I'm going to close this as I believe it's now automated through Salesforce.
