### ISSUE TITLE
Hide hidden resource pages from search

### ISSUE THREAD

**Issue by cyberteenie** [yalla-coop/shannon-trust-website#58]
**Is your feature / client request related to a problem? Please describe.**
Users can find hidden resources pages via search

**Describe the solution you'd like**
That pages are hidden from search

**Describe alternatives you've considered**

**Additional context**

**Comment by RamyAlshurafa** [comment]
Done @cyberteenie 
can you check again please?

**Comment by cyberteenie** [comment]
@RamyAlshurafa thanks! I have asked the client to check and will let you know.

**Comment by cyberteenie** [comment]
This has been confirmed as fixed by the client.
