### ISSUE TITLE
Add Images

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/shannon-trust-website#6]
### Further info
Get all the initial images we have into webflow so we don't have to worry about exports during development 

---

### Acceptance criteria

- [ ] Upload all images using the zip file to be added here
- [ ] Do a scan of all the wireframes just to check on your side that nothing has been missed. If so get in touch with design team
- [ ] As a note for when providing the ability for ST to upload images, always ensure there is a field for them to add the alt text (for accessibility reasons)

---

### To be added by design 

- [x] Hey @bethanyios can you upload a zip file of all the images please (either a zip file or a link to a download from your Google drive) 
    - [x] Ensure a clear naming convention (maybe just in line with figma so they can be matched) to help development team (and Shannon Trust content team) find them easily

**Comment by bethanyios** [comment]
Here are the images https://drive.google.com/drive/folders/1lh6CEw9UVzTrvabVxoE8A1JDidJdDBw6?usp=sharing

Naming convention:
**page-section (type)**

4 need to be located and there may be a couple more to add
