### ISSUE TITLE
Limit size of boxes on news and views and stories pages

### ISSUE THREAD

**Issue by cyberteenie** [yalla-coop/shannon-trust-website#60]
**Is your feature / client request related to a problem? Please describe.**
Client wants boxes on the news and views, and stories pages to all be the same size.

**Describe the solution you'd like**
Perhaps a cap on the number of characters for the title and caption?

**Describe alternatives you've considered**

**Additional context**
![Screenshot (64)](https://user-images.githubusercontent.com/97453274/150797708-922afd2d-18a0-4a09-9f9f-1e6ce5f038b0.png)

**Comment by RamyAlshurafa** [comment]
Done @cyberteenie

**Comment by cyberteenie** [comment]
@RamyAlshurafa - thanks! I will let client know and close the issue once they have approved it

**Comment by cyberteenie** [comment]
@RamyAlshurafa -
They have confirmed that the boxes are now working but are wondering if it would be possible to have all the "read more" links in a line. Or if that’s not a possibility, as they are not sure if that will look right, could they instead have the headings as links to the full article instead? Using Age UK as an example for :  https://www.ageuk.org.uk/discover/

Also, when you click on ‘stories’ it’s automatically filtering to fundraising – can this be changed, please, so that it’s going to all?

**Comment by RamyAlshurafa** [comment]
Done @cyberteenie 
i made the links in a line

**Comment by cyberteenie** [comment]
Thanks Ramy - I have let the client know.

**Comment by cyberteenie** [comment]
Client confirmed that they are happy with the fix.
