### ISSUE TITLE
Quotes carosel moving too fast to be able to read

### ISSUE THREAD

**Issue by cyberteenie** [yalla-coop/shannon-trust-website#61]
**Describe the bug**
the quotes carousel moves through too fast to the next quote to be able to read
Please slow down!

**Team - do not edit**
@thejoefriel
@RamyAlshurafa

**Comment by cyberteenie** [comment]
@RamyAlshurafa - client is happy with 12 seconds. Thank you!

**Comment by RamyAlshurafa** [comment]
Hey @cyberteenie 
done

**Comment by cyberteenie** [comment]
@RamyAlshurafa - the carousel on the corporate page still needs updating. Thanks!

**Comment by cyberteenie** [comment]
Client confirmed that it is working.
