### ISSUE TITLE
add a first and surname field to the newsletter sign up that’s in the footer

### ISSUE THREAD

**Issue by cyberteenie** [yalla-coop/shannon-trust-website#62]
**Is your feature / client request related to a problem? Please describe.**
Client would like to use the name parameters to make more customised emails

**Describe the solution you'd like**
add a first and surname field to the newsletter sign up that’s in the footer

**Team - do not edit**
@thejoefriel
@RamyAlshurafa

**Comment by RamyAlshurafa** [comment]
Hey @cyberteenie 
this is done now, ive used `First name` / `Last name` labels to match the fields they have in their audience dashboard in Mailchimp, we can display them in a different way in webflow if they want

**Comment by cyberteenie** [comment]
Client confirmed that she is happy with how it looks.
