### ISSUE TITLE
Order Resources Page showing as search result on Google

### ISSUE THREAD

**Issue by cyberteenie** [yalla-coop/shannon-trust-website#68]
Coming via email from client. 

**Describe the bug**
the ‘order resources’ page is showing up through Google, even though it’s a hidden page.

**To Reproduce**
Google ‘ Turning Pages Shannon Trust’  & then clicked on ‘Order Resources – Shannon Trust’ which takes you to the prison order form .

**Expected behavior**
Only people registered on Salesforce should access that page. It should not come up in a Google search.

**Team - do not edit**
@thejoefriel
@RamyAlshurafa

**Comment by RamyAlshurafa** [comment]
Hey @cyberteenie 
we can hide the page from search engines but we can't restrict the access  and allow it just to the people who have registered in Salesforce

**Comment by cyberteenie** [comment]
@RamyAlshurafa - quick question before I inform the client - would it be possible to protect this page via password?

**Comment by RamyAlshurafa** [comment]
Hey @cyberteenie 
done, if it still appears on Google results, it will be taken down in a few days when Google engines reindex the website

**Comment by cyberteenie** [comment]
Waiting for client to confirm it is working on their end (via email).

**Comment by cyberteenie** [comment]
@RamyAlshurafa - client has confirmed that the order resources page is now hidden, but the resources page is still showing. Can you please hide the resources page as well?

**Comment by RamyAlshurafa** [comment]
done now, it may take up to few days to be taken down from search results

**Comment by cyberteenie** [comment]
Confirmed as working by client
