### ISSUE TITLE
Order resources form showing minus quantities 

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#69]
**Please select the priority level by adding one of the following labels to this issue**
- Priority-3 

**Describe the bug**
On the order resources form, people are able to click negative quantities, which is causing an error with Zapier and people's orders aren't going through. Are we able to make sure we can't input negative quantities?

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem or a link to a Loom recording of the video

![Screenshot (107)](https://user-images.githubusercontent.com/107695201/176244381-7da1133a-6686-4524-95c7-f81b43856a9a.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Team - do not edit**
@thejoefriel
@RamyAlshurafa

**Comment by cyberteenie** [comment]
Hi @ShannonTrust - we will look into this! Thanks!

**Comment by RamyAlshurafa** [comment]
done @cyberteenie

**Comment by cyberteenie** [comment]
@ShannonTrust - this is not ready for you to test! Feel free to close the issue when you have confirmed that it is working on your side.

**Comment by cyberteenie** [comment]
@ShannonTrust - just updated a typo from my last comment...
It should say "now" ready to test! Not " not" !
