### ISSUE TITLE
Add Icons

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/shannon-trust-website#7]
### Further info
Get all the initial images we have into webflow so we don't have to worry about exports during development 

---

### Acceptance criteria

- [x] Add all icons using the zip file to be added here

---

### To be added by design 

- [ ] Hey @bethanyios can you upload a zip file of all the icons please (either a zip file or a link to a download from your Google drive) 
    - [ ] Ensure a clear naming convention (maybe just in line with figma so they can be matched) to help development team (and Shannon Trust content team) find them easily 
    - [ ] Ensure they are all svg files

**Comment by bethanyios** [comment]
Here are the icons https://drive.google.com/drive/folders/1S6fFSWqYeFK4FU6RfPqp7zH6BhI9IzsS?usp=sharing
