### ISSUE TITLE
Confirmation email after submitting an order

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#70]
**Is your feature / client request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

On our old website, people who were submitting an order for the resources would get a confirmation email so they could look back on what they had ordered and when. Since having the new website, we have had a lot of people coming back to us to check what they have ordered.

**Describe the solution you'd like**

Would it be possible for people to have a confirmation email when they have made an order through the order resources form?

**Describe alternatives you've considered**

**Additional context**

**Team - do not edit**
@thejoefriel
@RamyAlshurafa

**Comment by cyberteenie** [comment]
Thanks @ShannonTrust - I have handed this off to the dev team!

**Comment by thejoefriel** [comment]
Hi @ShannonTrust @cyberteenie there are a couple of approaches on how to do this, depending on what you prefer:

**Option 1 - Set up the emails in Salesforce**
Salesforce has the option to set up automated emails that get sent, triggered by certain events. There are some more detaisl on this here: https://help.salesforce.com/s/articleView?id=sf.customize_wfalerts.htm&type=5 

The benefits of this are you keep things in your chosen CRM

Downside is that we aren't Salesforce experts. We would be happy to get a log in to your Salesforce to have a look at setting this up for you but we can't estimate how long it might take to complete

**Option 2 - Add a final step to send an email in Zapier, using an integration like Sendgrid**
We can add a final step in the Zapier integration to send an email using a third party provider like Sendgrid, which is a free app you can integrate with Zapier. Sendgrid offers a free service up to 100 emails per day, so should easily meet your needs. 

Downsides:
- Talking to Chris you may want to move away from Zapier in the medium future, which if you do would mean we would need to redo this work

Time to complete: 0.5 to 1 day


---

Hope that is helpful. Let me know if you'd like me to proceed!

**Comment by ShannonTrust** [comment]
Hi @thejoefriel, I spoke to Chris and he said it should be fairly easy to set up an email in Salesforce and we should be able to do it ourselves. The only issue is is that we don't currently ask for email addresses on the order form. Would this be fairly easy to add and then amend the Zap?

**Comment by cyberteenie** [comment]
@ShannonTrust - let me follow up with Joe on this and let you know. Thanks!

**Comment by thejoefriel** [comment]
Hey @ShannonTrust - we can add an email address input to the Webflow form fairly easily. 

The bigger issue though is where to put it in Salesforce. You need to decide in which Salesforce object the email would be stored (i.e. is it in the client record, the order record etc?). Depending on the choice you make we may then need to alter the Zap quite a bit (e.g. if in client record, we'll need to update every record if there's no email address to then store and email address, or if it's different to replace it / or if it's in the order record, then we need to know the field so we can store it there)

Did you want to have a chat internally on this? We can then jump on a quick call to talk through if you like :)

**Comment by ShannonTrust** [comment]
Hi @thejoefriel, I believe Chris is going to get in touch to discuss options.

**Comment by thejoefriel** [comment]
Hey @ShannonTrust , I don't think I heard from Chris on this. We've spoken more widely about Salesforce but not specifically  this email issue. Did we want to arrange a time for next week?

**Comment by cyberteenie** [comment]
@ShannonTrust - just bumping Joe's question above! Thanks!

**Comment by ShannonTrust** [comment]
Hi @thejoefriel, I did follow up on this with Chris the other week. He said he had a solution in mind but needed to do some testing first. I'll follow up with him again and see where he's at.

**Comment by thejoefriel** [comment]
OK sure thing thanks @ShannonTrust - just let us know when you'd like to pick up conversations on it with us. Speak soon!

**Comment by ShannonTrust** [comment]
Closing this as we've found a solution another way.
