### ISSUE TITLE
Hyphens showing in search results

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#71]
**Please select the priority level by adding one of the following labels to this issue**
Priority-3 (Normal e.g. Text is missing / duplicate values being shown)

**Describe the bug**
After doing a Google search, some of the page titles are coming up with hyphens between the words. For example, 'about-us', 'learn-to-read'

**To Reproduce**

**Expected behavior**
Can we have it so that it doesn't show hyphens.

**Screenshots**
![Screenshot (117)](https://user-images.githubusercontent.com/107695201/183434070-c392a262-be64-4fc8-91d6-daba46c8b11f.png)
![Screenshot (116)](https://user-images.githubusercontent.com/107695201/183434075-0fc8b6df-f3f1-421d-8b14-d1933f3d150b.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome and Microsoft Edge

**Smartphone (please complete the following information):**

**Additional context**

**Team - do not edit**
@thejoefriel
@RamyAlshurafa

**Comment by cyberteenie** [comment]
@ShannonTrust - thanks for flagging. We will get this done and let you know when it is ready to test.

**Comment by RamyAlshurafa** [comment]
done and published

Note: it may take up to 2 days to update Google's results

**Comment by ShannonTrust** [comment]
Thanks, @RamyAlshurafa. I'll check on Friday before closing.

**Comment by cyberteenie** [comment]
@ShannonTrust - this will be ready to check now!

**Comment by ShannonTrust** [comment]
This looks like it's all good now. Thank you
