### ISSUE TITLE
Changing volunteer role title

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#73]
**Is your feature / client request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
Ex. I'm always frustrated when [...]
Ex. We need to delete a user [...]

**Describe the solution you'd like**
We recently changed the title of one of our volunteer roles from 'area secretary' to 'area administrator'. I've changed the name in the role description, but could you change it in the application form, please?

**Describe alternatives you've considered**

**Additional context**

![Screenshot (120)](https://user-images.githubusercontent.com/107695201/184638743-405f0889-bd57-4626-a033-65bb2dd8c184.png)

**Team - do not edit**
@thejoefriel
@RamyAlshurafa

**Comment by cyberteenie** [comment]
@ShannonTrust - will do!

**Comment by RamyAlshurafa** [comment]
Done and published
@ShannonTrust can you ask us to change the roles in the future please, as this breaks the form functionality

**Comment by ShannonTrust** [comment]
Thanks, @RamyAlshurafa. And will do.
