### ISSUE TITLE
Adding pronoun option to volunteer application form

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#74]
**Is your feature / client request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
Ex. I'm always frustrated when [...]
Ex. We need to delete a user [...]

**Describe the solution you'd like**
It would be good if we can include a pronoun option on the application form to avoid making assumptions and possibly getting it wrong. I don't know if it would be best to have tick boxes, or to have a free text box for people to input their own. Happy for you to offer your opinions.

**Describe alternatives you've considered**

**Additional context**

**Team - do not edit**
@thejoefriel
@RamyAlshurafa

**Comment by cyberteenie** [comment]
Hi @ShannonTrust - I will hand this off to the dev team and they will be in contact concerning format. Thanks!

**Comment by RamyAlshurafa** [comment]
done, published here https://shannon-trust.webflow.io/volunteer
if you are happy with the change we can deploy to the website

**Comment by cyberteenie** [comment]
@ShannonTrust - feel free to test and let us know if you have any issues!

**Comment by ShannonTrust** [comment]
Thanks for doing this, @RamyAlshurafa. Could you change the heading so it's lowercase and add a question mark - 'What are your pronouns?'. Other than that, we're happy with how it looks.

**Comment by cyberteenie** [comment]
I will follow up with Ramy on this!

**Comment by RamyAlshurafa** [comment]
Hey @ShannonTrust 
sure thing will update the heading

regarding the other option, yeah that's possible, but that field will be coming as a different field e.g "pronouns_other", is that fine?

**Comment by cyberteenie** [comment]
@ShannonTrust - just wanted to bump Ramy's question above - is ok if the additional pronouns come through as a separate field?

**Comment by ShannonTrust** [comment]
Thanks, @RamyAlshurafa. I don't see any issue with it being in a different field, I can let the team know how it will appear.

Sorry for the delay in getting back to you, just got back from annual leave so catching up with everything now!

**Comment by cyberteenie** [comment]
@ShannonTrust - thanks for letting us know! We will go ahead and do this. Hope you had a nice time away!

**Comment by RamyAlshurafa** [comment]
Hey @ShannonTrust 
the change has been published, can you check, please?

**Comment by ShannonTrust** [comment]
Perfect, thank you!
