### ISSUE TITLE
Make Heading 2 a bit smaller

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#75]
**Please select the priority level by adding one of the following labels to this issue**
- Priority-4 (Low e.g. Content is not perfectly aligned)

**Describe the bug**
For the blog posts, Heading 2 looks the same size as Heading 1 when it should be smaller.

**To Reproduce**

**Expected behavior**
Could we make Heading 2 a bit smaller than Heading 1 so there's no confusion about whether it's a subheading or not.

**Screenshots**
![Screenshot (121)](https://user-images.githubusercontent.com/107695201/184641263-83af613e-f9eb-48fc-9f73-926aeb67e5ab.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Team - do not edit**
@thejoefriel
@RamyAlshurafa

**Comment by cyberteenie** [comment]
@ShannonTrust - noted, and will do!

**Comment by RamyAlshurafa** [comment]
Done and published

**Comment by ShannonTrust** [comment]
Thanks, @RamyAlshurafa
