### ISSUE TITLE
New volunteer role

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#76]
**Is your feature / client request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
Ex. I'm always frustrated when [...]
Ex. We need to delete a user [...]

**Describe the solution you'd like**
Now that we're getting ready for the app launch, we'd like to add the 'Digital reading coach' role to the main volunteer page. However, we don't want it linked to the application form on that page, as they'll need to sign up on a different platform. 

The buttons would need to be:
View role description (linked to: https://www.shannontrust.org.uk/become-a-coach)
Sign up as a coach (linked to: https://turningpages.co.uk/sign-up-as-coach)

**Describe alternatives you've considered**

**Additional context**
Can the new role be added underneath the current reading coach role. If you copy the current text, we can edit it once it's live.
![Screenshot (166)](https://user-images.githubusercontent.com/107695201/194068228-4d5ffa3f-84e6-4cce-ad92-77574fbaba0f.png)

**Team - do not edit**
@thejoefriel
@RamyAlshurafa

**Comment by RamyAlshurafa** [comment]
Done @ShannonTrust

**Comment by ShannonTrust** [comment]
Thanks @RamyAlshurafa. Would we be able to get rid of the 'locations available' bit just for this role?

**Comment by RamyAlshurafa** [comment]
Hey @ShannonTrust 
yeah sure thing,
removed now

**Comment by ShannonTrust** [comment]
Thanks, @RamyAlshurafa. Looks good now
