### ISSUE TITLE
Add reference field to volunteer form

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#77]
**Is your feature / client request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

We'd like to be able to collect referee details through the volunteer form, as currently we're doing this as another step after they've submitted the application.

**Describe the solution you'd like**

Could we have the below as 3 separate fields:
- Referees full name
- Referees email address
- Relationship to you

And can we have this guidance included as well, please:

As part of the recruitment process, we ask for references from all accepted volunteers. 

Please provide us with the details of your referee and their relationship to you. This is a character reference, so a friend or neighbour is ideal. We ask that you are not related to the referee and that they aren’t your partner. They must have known you for a minimum of 2 years. They will be asked to comment on your skills and attributes in relation to the volunteer role description. 

**Describe alternatives you've considered**

**Additional context**

**Team - do not edit**
@thejoefriel
@RamyAlshurafa

**Comment by cyberteenie** [comment]
@ShannonTrust Thanks I will pass this on to the development team!

**Comment by RamyAlshurafa** [comment]
![image](https://user-images.githubusercontent.com/34629478/194754907-92cb8034-787b-4755-9869-6c254156c0ce.png)

Hey @thejoefriel 
maybe i can use a similar style here, or I have to wait for you to do the designs?

**Comment by thejoefriel** [comment]
Sorry thought I'd replied to this. Yeah you can use the same style. Thanks!

**Comment by cyberteenie** [comment]
@RamyAlshurafa just tagging you here to make sure that you saw Joes response above!

**Comment by RamyAlshurafa** [comment]
Hey @ShannonTrust 
this is deployed to https://shannon-trust.webflow.io/volunteer 
if you are happy with the change we can deploy to original domain

**Comment by ShannonTrust** [comment]
Thanks, @RamyAlshurafa. Happy with the way it looks and for you to make it live on the website

**Comment by RamyAlshurafa** [comment]
@ShannonTrust 
done, can we close the issue now?

**Comment by ShannonTrust** [comment]
Thanks, @RamyAlshurafa
