### ISSUE TITLE
New webpage - employee benefits

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#78]
**Is your feature / client request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
Ex. I'm always frustrated when [...]
Ex. We need to delete a user [...]

**Describe the solution you'd like**
We would like to create a new page detailing our new employee benefits scheme. We have a few ideas in mind of how we would like it to look, but it would be good to put in a call to discuss what this will look like. 

**Describe alternatives you've considered**

**Additional context**

This is the copy that we would like to be include on the page:
[Web page benefits final.docx](https://github.com/yalla-coop/shannon-trust-website/files/9859765/Web.page.benefits.final.docx)

**Team - do not edit**
@thejoefriel
@RamyAlshurafa

**Comment by cyberteenie** [comment]
@ShannonTrust sounds good! I will speak to the team and get back to you with some possible times for a call.

**Comment by cyberteenie** [comment]
Hi @ShannonTrust - I just wanted to update you and let you know that @jema28 will be in touch about organising a call in the next weeks. Thanks!

**Comment by ShannonTrust** [comment]
Hi @cyberteenie, thanks for the update.

**Comment by jema28** [comment]
Hi @ShannonTrust, 

I hope you’re well! Sorry for the delay, have been travelling.
 
I’ll be back next week so can meet anytime on Wednesday if that works for you? 

Cc @cyberteenie

**Comment by ShannonTrust** [comment]
Hey @jema28, Wednesday works for us. We can do anytime between 9am and midday, or after 3pm. Let me know what works best for you and I'll send you an invite.

**Comment by jema28** [comment]
Okay great, thanks @ShannonTrust. I've got meetings in the morning but am free at 3pm, look forward to it.

**Comment by ShannonTrust** [comment]
Sorry, @jema28, is there a day and time you're free next week instead? Amy is now all booked up for Wednesday and then she's off Thursday and Friday. Thanks

**Comment by jema28** [comment]
Hey @ShannonTrust, no worries! Sure thing, I'm free on Tuesday at 1:30pm - 2:30pm or first thing between 9am - 11am. Do any of those work for you?

**Comment by cyberteenie** [comment]
@ShannonTrust just wanted to bump Jem's response above, in case you didn't see it!

**Comment by jema28** [comment]
@cyberteenie Thanks! Megan sent me an invite for next week so all good on this :)

**Comment by jema28** [comment]
Hey @ShannonTrust 

Thanks for our call earlier! Here's a quick summary:

**Employer page to include:**
- An introduction with a video embed
- Icons and text cards similar to the Fundraise page
- Call to action saying "Check out our latest vacancies" and a link to the vacancies
- Two buttons at the bottom: Work for us and Volunteer

This page doesn't need to be in the navbar. Will be linked from the Work of us page but Megan/Amy will sort this on their end. 

I'll get on this this week and then pass over to the dev team next week. We discussed a rough deadline of two weeks from today to get this live. We'll let you know if this needs to be adjusted. 

cc @cyberteenie

**Comment by ShannonTrust** [comment]
Thanks, @jema28. Here is the final copy for the webpage: 
[Employee benefits webpage final.docx](https://github.com/yalla-coop/shannon-trust-website/files/10066237/Employee.benefits.webpage.final.docx)

And this is the Nationwide page we mentioned that we liked: https://www.nationwide-jobs.co.uk/benefits/

**Comment by jema28** [comment]
Hey @ShannonTrust,

Hope you had a good weekend. 

Here's the page for your review: https://www.figma.com/file/vC6iqpWqeTJSPkM0Lswcfp/Shannon-Trust---Website?node-id=2401%3A11411&t=xRpkrcAJHdn48QNR-1

Thanks for the nationwide link, I used as inspiration for one of the sections. Let me know if you'd like any tweaks? Once you're happy I'll pass over to the dev team. Thanks!

**Comment by jema28** [comment]
Hi @ShannonTrust, I've just made the requested changes, thanks for those. Let me know if you and Amy are happy for me to give this to dev? We'll probably need an extra week to get this live once confirmed but we'll keep you updated.

**Comment by ShannonTrust** [comment]
Hi Jem,

Looks good to me – will flag with Megan after lunch to check she is happy too and then we can go ahead.

Kind regards,

Amy Longstaff
Communications and Fundraising Manager

Tel: 020 3764 5251
Mobile: 07561165119
Mailing address: FREEPOST Shannon Trust

***@***.***


Twitter<https://twitter.com/Shannon_Trust> | Facebook<https://www.facebook.com/ShannonTrustCharity/> | Web<http://www.shannontrust.org.uk/> | LinkedIn<https://www.linkedin.com/company-beta/8654000/> | Instagram<https://www.instagram.com/shannontrustcharity/>

Registered address: Shannon Trust, International House, 24 Holborn Viaduct, London, EC1A 2BN
Registered Charity no. 1117249

At Shannon Trust we work flexible hours. Please note that if you receive an email from me in the evening or at a weekend there is not an expectation for you to respond outside of your own working hours.

**Comment by ShannonTrust** [comment]
Thanks, @jema28. All looks good!

**Comment by jema28** [comment]
Great, thank you both! 

@cyberteenie @RamyAlshurafa this page is now ready for dev. Could you please write an update progress here when it's ready for Megan and Amy to review. Thanks :)

**Comment by RamyAlshurafa** [comment]
Hey @jema28 
can you export the background images used in these cards please (with  the overlay colour) 
<img width="828" alt="image" src="https://user-images.githubusercontent.com/34629478/207283064-95138541-a031-46b3-b8a6-4ff4cd8a62c1.png">

**Comment by jema28** [comment]
Here you go @RamyAlshurafa :)

[ST Employer Benefits page.zip](https://github.com/yalla-coop/shannon-trust-website/files/10230175/ST.Employer.Benefits.page.zip)

**Comment by cyberteenie** [comment]
Thanks @jema28 - will do. I have passed this off to the dev team. I will update as we go!

**Comment by RamyAlshurafa** [comment]
Thanks @jema28 

@ShannonTrust the page is ready for your review now https://shannon-trust.webflow.io/employee-benefits
once you approve i can publish to the production domain

Thanks

**Comment by ShannonTrust** [comment]
Thanks, @RamyAlshurafa. The font size under 'what we do' seems to be bigger than the rest of the page, could this be changed, please?

**Comment by cyberteenie** [comment]
@ShannonTrust I will make sure that the team sees your comment!

**Comment by RamyAlshurafa** [comment]
done @ShannonTrust 
 let me know if its all good  now please

**Comment by ShannonTrust** [comment]
Thanks, @RamyAlshurafa. All looks good from our end and is ready to go live

**Comment by RamyAlshurafa** [comment]
Thanks @ShannonTrust
sorry for the late notification, but this has been published and is live now

**Comment by ShannonTrust** [comment]
Ignore me. I've managed to figure it out!

**Comment by RamyAlshurafa** [comment]
Sorry about this @ShannonTrust 
It's fixed now, can you check please?

**Comment by ShannonTrust** [comment]
Thanks, @RamyAlshurafa. All looks good now.
