### ISSUE TITLE
Changing field on resource form

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#79]
**Is your feature / client request related to a problem? Please describe.**
We previously asked for a confirmation email to come through after someone submits an order on the resources page. Chris is still looking at how we can do this through Salesforce, but we've come up with a solution for the short term and we'd like people to input their email into the form so we can send them a confirmation email.

**Describe the solution you'd like**
At the top of the form there's a field that says 'requested by' and in the box it has 'type name'. Could we change this to 'type name and email address'?

![Screenshot (171)](https://user-images.githubusercontent.com/107695201/201635915-8f31b66b-5747-4dd3-9e50-1609aae62328.png)

**Describe alternatives you've considered**

**Additional context**

**Team - do not edit**
@thejoefriel
@RamyAlshurafa

**Comment by cyberteenie** [comment]
@ShannonTrust - I will pass this off to the development team! Thanks!

**Comment by RamyAlshurafa** [comment]
Done @ShannonTrust https://www.shannontrust.org.uk/order-resources
can you check, please

**Comment by ShannonTrust** [comment]
Thanks, @RamyAlshurafa. All good!
