### ISSUE TITLE
Blue background doesn't fit title on mobile

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#80]
**Please select the priority level by adding one of the following labels to this issue**
- Priority-4 (Low e.g. Content is not perfectly aligned)

**Describe the bug**
Looking at the 'news and views' page on mobile, the title 'stay up to date on social' doesn't fit the blue background. 

**To Reproduce**
1. Go to 'news and views'
3. Scroll down to 'stay up to date on social'

**Expected behavior**

Title needs to fit in blue background.

**Screenshots**
If applicable, add screenshots to help explain your problem or a link to a Loom recording of the video
![Screenshot_20221207-123228](https://user-images.githubusercontent.com/107695201/206181379-e7e8795a-f736-478f-b9c1-f071dc1b7a32.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Team - do not edit**
@thejoefriel
@RamyAlshurafa

**Comment by cyberteenie** [comment]
@ShannonTrust noted! I will pass this off to the team! Thanks.

**Comment by RamyAlshurafa** [comment]
Fixed, @ShannonTrust can you check please

**Comment by ShannonTrust** [comment]
Thanks, @RamyAlshurafa
