### ISSUE TITLE
Cookie settings

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#81]
**Please select the priority level by adding one of the following labels to this issue**
- Priority-4 (Low e.g. Content is not perfectly aligned)

**Describe the bug**
We've had some feedback from people wanting to visit our website about our cookie options. Currently you only have the option to accept all cookies, is there an option to add a 'reject' or 'accept essential' buttons?

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem or a link to a Loom recording of the video
![Screenshot (177)](https://user-images.githubusercontent.com/107695201/207044386-d6f8ff64-5c76-482b-b7b8-ddae2c80d44a.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Team - do not edit**
@thejoefriel
@RamyAlshurafa

**Comment by cyberteenie** [comment]
@ShannonTrust let me get an estimate for you for this request! Thanks!

**Comment by RamyAlshurafa** [comment]
time estimation: 1-2 hours

**Comment by cyberteenie** [comment]
@ShannonTrust if you are happy with the estimate above and would like to move forward with this task, please confirm below. Thanks!

**Comment by ShannonTrust** [comment]
Thanks, @cyberteenie and @RamyAlshurafa. Are we still in credit with the SLA?

**Comment by cyberteenie** [comment]
@ShannonTrust the report is due in a couple of days so I will let you know once that is all calculated! Thanks!

**Comment by cyberteenie** [comment]
@ShannonTrust I am happy to report that we are still in credit and will get going on this feature as soon as possible! Thanks!

**Comment by ShannonTrust** [comment]
Great. Thanks for letting us know.

**Comment by RamyAlshurafa** [comment]
Hey @ShannonTrust 
this has been done now, can you check, please?
<img width="1770" alt="image" src="https://user-images.githubusercontent.com/34629478/212554046-7dab5af2-8158-4c26-a766-d0c3c791f501.png">

**Comment by ShannonTrust** [comment]
Thanks for sorting, @RamyAlshurafa.
