### ISSUE TITLE
Apply Webflow charity discount

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#83]
**Is your feature / client request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
Ex. I'm always frustrated when [...]
Ex. We need to delete a user [...]

**Describe the solution you'd like**
Could you apply the discount code that we received to our Webflow account, please? @cyberteenie, you we copied into the email that has the code included. 

**Describe alternatives you've considered**

**Additional context**

**Team - do not edit**
@thejoefriel
@RamyAlshurafa

**Comment by cyberteenie** [comment]
@ShannonTrust i have passed that off to the team, thanks!

**Comment by cyberteenie** [comment]
Note: emailed on Jan 9th and 16th regarding payment details.

**Comment by cyberteenie** [comment]
[How to apply the discount code to Webflow](https://help.webflow.com.cach3.com/article/how-do-i-redeem-or-apply-a-coupondiscount-code?URL=http%3A%2F%2Fhelp.webflow.com.cach3.com%2Farticle%2Fhow-do-i-redeem-or-apply-a-coupondiscount-code#:~:text=From%20your%20Account%20settings%2C%20navigate,Was%20this%20helpful%3F)

**Comment by cyberteenie** [comment]
Coupon applied but confirmation not received.

**Comment by cyberteenie** [comment]
Closed as confirmed as applied by Megan
