### ISSUE TITLE
Order resources form update

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#84]
**Please select the priority level by adding one of the following labels to this issue**
- Priority-4 

**Describe the bug**
A little while a go we asked to have the email added to the order resources form, but it seems to be sending a bit of a glitch to Salesforce by also having the name added as well. Where we have 'requested by' could we just have 'type email address', please? That should then solve the issue.

**To Reproduce**
1. Go to '[...](https://www.shannontrust.org.uk/order-resources)'
2. Scroll down to 'requested by'
3. See issue

**Expected behavior**

Have email address option only

**Screenshots**
If applicable, add screenshots to help explain your problem or a link to a Loom recording of the video

<img width="539" alt="Resources order form" src="https://user-images.githubusercontent.com/107695201/216004235-2e983620-bb04-486c-a20d-49ecc44dd24a.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Team - do not edit**
@thejoefriel
@RamyAlshurafa

**Comment by cyberteenie** [comment]
@ShannonTrust I will let the dev team know! Thanks!

**Comment by ShannonTrust** [comment]
Thanks, @RamyAlshurafa
