### ISSUE TITLE
Check on Cookie bot Pricing

### ISSUE THREAD

**Issue by cyberteenie** [yalla-coop/shannon-trust-website#88]
Check to see what Cookiebot premium plan they will need to upgrade to.
via email from Media email address,

Email forwarded to Ramy

**Team - do not edit**
@thejoefriel
@RamyAlshurafa

**Comment by cyberteenie** [comment]
Ramy to look into this and respond to email thread.

**Comment by cyberteenie** [comment]
media email address needs approval to access Google file

**Comment by RamyAlshurafa** [comment]
Hey @cyberteenie 
unfortunately it doesn't show the price, it requires to fill the payment details, 
I suggest the ST team to contact the support and ask them about the price, what do you think?
<img width="811" alt="image" src="https://user-images.githubusercontent.com/34629478/234303840-ada2f20e-09b6-43ae-b12d-5ddc76023e06.png">

**Comment by cyberteenie** [comment]
@RamyAlshurafa Thank you for your help! I will let them know.

**Comment by cyberteenie** [comment]
Sent them an email asking them to Cookiebot support to find out the pricing

**Comment by cyberteenie** [comment]
Closing this issue for now, but will reopen if needed. I have emailed the media account just to make sure that they received my last email.
