### ISSUE TITLE
Update Google Analytics

### ISSUE THREAD

**Issue by cyberteenie** [yalla-coop/shannon-trust-website#89]
Google Analytics is due to deprecate UA (in favour of GA4) on 1st July https://support.google.com/analytics/answer/11583528?hl=en#:~:text=Google%20Analytics%204%20is%20our,4%20as%20soon%20as%20possible.

Before that we need to update Google Analytics so we're using GA4 rather than UA.

**Team - do not edit**
@thejoefriel
@RamyAlshurafa

**Comment by thejoefriel** [comment]
![image](https://github.com/yalla-coop/shannon-trust-website/assets/19708921/1c27410f-9c1d-4ff3-a74c-36df0efae48d)

**Comment by thejoefriel** [comment]
Hey @cyberteenie just putting this screenshot here as confirmation that GA seems to be working
