### ISSUE TITLE
Blog Post - Stories

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/shannon-trust-website#9]
__Further info__

This is part of the Stories CMS collection

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [x] Create this page in line with wireframes https://www.figma.com/file/vC6iqpWqeTJSPkM0Lswcfp/Shannon-Trust---Website?node-id=214%3A506
- [x] Please refer to text limits in Figma comments
- [x] Please follow prototype links in Figma
    - [x] Two links at the bottom of every post is always Stories and How you can help

**Required Fields**
- [x] Title
- [x] Author name
- [x] Publication date (default to today if no date put in)
- [x] Text (rich text editor)
- [x] Category/tag 
    - [x] At least one tag/category must be selected
    - [x] Multiple category/tags can be selected
    - [x] There is a total of 6 tags

**Optional Fields**
- [x] Image - if not provided fall back to placeholder https://www.figma.com/file/vC6iqpWqeTJSPkM0Lswcfp/Shannon-Trust---Website?node-id=956%3A7384
    - [ ] Minimum image size = 1440 x 752px (we need to ensure big images are added to ensure high quality for the top)
- [x] Audio file / link (depending on what is best to make this work). Only one audio can be added
- [x] Video file / link (depending on what is best to make this work). Only one video can be added 
- [x] Featured - this will always make it appear at the top of the Stories section

**Comment by thejoefriel** [comment]
Hey @RamyAlshurafa regarding the quotes. Instead of having just one featured quote (as a separate input field) ST would prefer that we use the rich text editor for the text, to include the quotation option, and then if quotation is used, then style it in the way the quote is shown in the wireframes. This would let them have multiple quotes in an article (good for long articles) and also not be limited to it always being third paragraph. 

Do you envisage any major issues with this?

**Comment by RamyAlshurafa** [comment]
Hey @thejoefriel 
yeah i did that, so when they add quotes in rich text it automatically show it in the custom style

- pure https://shannon-trust-website.webflow.io/stories/5-principles-of-effective-web-design
- audio https://shannon-trust-website.webflow.io/stories/10-things-nobody-told-you-about-being-a-web-designer
- video https://shannon-trust-website.webflow.io/stories/7-things-about-web-design-your-boss-wants-to-know
- without image: https://shannon-trust-website.webflow.io/stories/14-common-misconceptions-about-web-design

**Comment by RamyAlshurafa** [comment]
Hey @thejoefriel  
regarding this:
> Minimum image size = 1440 x 752px (we need to ensure big images are added to ensure high quality for the top)

I'm afraid we can't validate that, I have added a helper text for them when they upload pictures to tell them to check image size,  also will add a note in the training issue on how to check image's size
