### ISSUE TITLE
Spacing issue on mobile - fundraising resources

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#90]
**Please select the priority level by adding one of the following labels to this issue**
- Priority-3 (Normal e.g. Text is missing / duplicate values being shown)

**Describe the bug**
Fundraising resources on 'Fundraise your way' and 'Challenges and events' has weird spacing issues on mobile.

**To Reproduce**
1. Go to 'https://www.shannontrust.org.uk/fundraise-your-way  or  https://www.shannontrust.org.uk/challenges-events'
3. Scroll down to 'Fundraising resources'

**Expected behavior**
Text to be in the center of the boxes

**Screenshots**
If applicable, add screenshots to help explain your problem or a link to a Loom recording of the video

![Screenshot_20230602-091205](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/1020f1db-618e-4c74-b09c-c40a50f63510)
![Screenshot_20230602-091220](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/1af58211-60d1-4670-a4e5-984543f80c6c)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Team - do not edit**
@thejoefriel
@RamyAlshurafa

**Comment by cyberteenie** [comment]
@ShannonTrust - Thanks for flagging. I will pass that off!

**Comment by ShannonTrust** [comment]
Hi @cyberteenie, do you know when this might be fixed?

**Comment by cyberteenie** [comment]
@ShannonTrust - this is scheduled to be completed before the next reporting cycle. Thanks!

**Comment by RamyAlshurafa** [comment]
Hey @ShannonTrust 
this is done now, can you check please

**Comment by ShannonTrust** [comment]
Thanks, @RamyAlshurafa. All looks good.
