### ISSUE TITLE
Migrate Shopify over to GA4

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#91]
**Is your feature / client request related to a problem? Please describe.**
With Google Analytics changing, we'd like to make sure we're still tracking Shopify traffic (https://shop.turning-pages.co.uk/) as well as our website traffic.

I think Joe has all the details for the Shopify site.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Team - do not edit**
@thejoefriel
@RamyAlshurafa

**Comment by cemalokten** [comment]
@cyberteenie @RamyAlshurafa Google Analytics is currently setup for turning-pages-reading-programme.myshopify.com, however the URL used by ST is https://shop.turning-pages.co.uk/

Should I replace the old URL with the new? or is tracking still in place even if the DNS is redirecting it?

**Comment by thejoefriel** [comment]
In Google Analytics you need it to track the actual url so shop.turning-pages I believe. However, please email Chris to double check before you proceed

**Comment by cyberteenie** [comment]
@cemalokten I will email Chris and ST and copy you in on the email.

**Comment by cyberteenie** [comment]
@cemalokten - as per the email thread, let's update, but keep the setup as close to it was as possible. That means staying with http://turning-pages-reading-programme.myshopify.com/

Before making any changes, please take a few screenshots of the set up and document them here in case we need to revert anything.

**Comment by cemalokten** [comment]
@cyberteenie I've left the setup as it was, set to http://turning-pages-reading-programme.myshopify.com/ - ready for review

**Comment by thejoefriel** [comment]
Hey @cyberteenie here's a screenshot of Shopify. It seems to have picked up the traffic and is working now: 
![image](https://github.com/yalla-coop/shannon-trust-website/assets/19708921/e06df411-0a7d-40ad-a419-947d7d07c42f)
