### ISSUE TITLE
WEEKLY CHORE: Log Sentry bugs every Sunday

### ISSUE THREAD

**Issue by cyberteenie** [yalla-coop/shannon-trust-website#92]
Log in to Sentry and log any bugs as a new SLA issue in Github.
Each bug should be logged as an individual issue unless they are related to one another.
Confirm that you have logged the issues by ticking the checkbox below.

July 2023
- [ ] Week 1
- [ ] Week 2
- [ ] Week 3
- [ ] Week 4

August 2023
- [ ] Week 1
- [ ] Week 2
- [ ] Week 3
- [ ] Week 4

September 2023
- [ ] Week 1
- [ ] Week 2
- [ ] Week 3
- [ ] Week 4

October 2023
- [ ] Week 1
- [ ] Week 2
- [ ] Week 3
- [ ] Week 4

November 2023
- [ ] Week 1
- [ ] Week 2
- [ ] Week 3
- [ ] Week 4

December 2023
- [ ] Week 1
- [ ] Week 2
- [ ] Week 3
- [ ] Week 4

**Comment by RamyAlshurafa** [comment]
Hey @cyberteenie 
we dont have sentry set up on this project(and for all webflow projects) as there is no codebase for it and not needed

**Comment by cyberteenie** [comment]
🙏

**Comment by adnan0afana** [comment]
@RamyAlshurafa @cyberteenie So is there any action required from my side about this (as I'm working Webflow)?

**Comment by cyberteenie** [comment]
@adnan0afana - no action needed. Thanks!
