### ISSUE TITLE
Onboard Fadi and Adnan to project

### ISSUE THREAD

**Issue by cyberteenie** [yalla-coop/shannon-trust-website#94]
### Is your feature / client request related to a problem? Please describe.

Fadi will be taking over as dev lead on this webflow project. He will need to be onboarded. Adnan will be tech assistant and back up lead so should be onboarded as well.

**Comment by RamyAlshurafa** [comment]
waiting for @fadeomar @adnan0afana to book a time

**Comment by fadeomar** [comment]
hey @RamyAlshurafa I've booked the next Sunday 20/8 at 11:30 Gaza time and invite you and @adnan0afana  for the meeting, see you soon
