### ISSUE TITLE
Volunteer page enhancement

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#96]
### Ask your question here.

I've been talking to our volunteer manager about making some changes to our volunteer page, but I'm unsure what's possible. Previously, you’ve said we can’t make changes to the volunteer application form, but we’d like to add training dates to the end with a ticket box to say that people can attend all dates, and we’d like to be able to edit the dates. Is there a way that we’d be able to do this?

**Comment by cyberteenie** [comment]
@ShannonTrust - I will have a chat with the team and get back to you on this!

**Comment by RamyAlshurafa** [comment]
Hey @ShannonTrust 
yeah we can update the form from our side, and then we will need Chris to update the salesforce data.
can you provide what is the copy please?

**Comment by ShannonTrust** [comment]
Thanks, @RamyAlshurafa. At the bottom of the forms for the prison volunteer, area coordinator and area administrator roles can add: 

Closing date for next application round: 28 August

Essential volunteer induction training: 27 September, 4, 11, 18 October

Then a tick box underneath saying: 'I am able to attend volunteer training on the above dates' 

We'd like to be able to change these dates ourselves.

**Comment by ShannonTrust** [comment]
@RamyAlshurafa, we'd also like to add in another text box above the form as well if possible. It can follow the same style as the rest of the page and the heading will be 'Recruitment and training'

![Screenshot (236)](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/13d519e3-0115-4464-bc53-b99b3208d087)

**Comment by cyberteenie** [comment]
@RamyAlshurafa - if you are please able to chat with @fadeomar about this tomorrow (Wednesday), that would be great as he is scheduled to complete it on Thursday. 🙏

**Comment by cyberteenie** [comment]
@ShannonTrust - we are just finishing off this issue now, but have a question for you. You have requested:
'we'd also like to add in another text box above the form as well if possible. It can follow the same style as the rest of the page and the heading will be 'Recruitment and training'.

For clarity, do you mean that this is just a heading text?
Or would it be a part of the form where people could type into?

**Comment by cyberteenie** [comment]
@ShannonTrust - for clarity, do you want something that looks a bit like this, but above the form and with the heading  'Recruitment and training', with some room for additional text below?
![Screenshot 2023-08-23 at 14 23 20](https://github.com/yalla-coop/shannon-trust-website/assets/97453274/59add31d-3d78-46b4-99ea-22607282ec6c)

**Comment by cyberteenie** [comment]
@ShannonTrust - one other thing. Should the checkbox be required?

**Comment by ShannonTrust** [comment]
Hi @cyberteenie, with regards to the recruitment and training text box, yes we would like to it be above the form like the 'in community' section you have highlighted. 

I'm not sure about if the checkbox needs to be a requirement, let me talk to our volunteer manager and get back to you.

**Comment by ShannonTrust** [comment]
Can we make the tick box a requirement, please. 

I've noticed that some of these changes have already been published to the main site. Just to clarify, we can change the closing and training dates ourselves, right? The closing date has now passed so I want to go in and update it to the current dates.

**Comment by bethanyios** [comment]
Hi @ShannonTrust thanks so much for clarifying. 

Here is the new addition to the form with dates, could you let us know if that is what you had in mind? If happy we will push that after making the checkbox required.

![Image](https://github.com/yalla-coop/shannon-trust-website/assets/36175966/9214f161-b531-4181-828d-9877e8d982f0)

Could you also provide us with the copy for the new section "Recruitment and Training" 

cc. @adnan0afana, @fadeomar

**Comment by ShannonTrust** [comment]
Thanks, @bethanyios, that's all good with us. 

The copy for the recruitment and training section is:

Thank you for your interest in joining our volunteer team.

The closing date for applications to attend our next round of training is 19 January 2024. 

We will respond to all applications. Successful applicants will be invited to interview during the weeks commencing 22 and 29 January. This is an opportunity for you to meet our regional team, to find out more about you and for us to share more information about the volunteering role. 

You'll be given high quality training to prepare you for volunteering with Shannon Trust. This takes place over 4 training sessions and via our online training portal. We ask that volunteers aim to complete the training in one course as this means that you will be ready to start actively volunteering.

The next training sessions for volunteering for people applying to be a prison volunteer, area coordinator or area administrator will take place 20, 27 February, 5, 12 March. Please check that you can attend the dates prior to applying. 

You’ll also receive the opportunity to attend ongoing training sessions and peer support meetings during your time as a volunteer to build your skills and experience.

**Comment by adnan0afana** [comment]
Hi @bethanyios @ShannonTrust I updated the section and used the copy send above, would you check
https://shannon-trust.webflow.io/volunteer

**Comment by ShannonTrust** [comment]
Hi @adnan0afana, that all looks good to us.

**Comment by adnan0afana** [comment]
@ShannonTrust Happy to hear that!
so should we publish this to the main domain?

**Comment by ShannonTrust** [comment]
Great. Thanks, @adnan0afana!
