### ISSUE TITLE
Add/change prison locations on order resource form

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#97]
### Is your feature / client request related to a problem? Please describe.

We've recently renamed some of the prisons on Salesforce and so need to change them on the resource ordering form on the website as well

### Describe the solution you'd like

HMP Isle of Wight has now been split into 2 sites, so we need to remove HMP Isle of Wight from the webform and replace it with:

HMP Isle of Wight – Albany
HMP Isle of Wight – Parkhurst

Also the 2 Feltham prisons have been renamed, so we need to rename on the webform:

HMYOI Feltham is now HMYOI Feltham (A side)
HMP Feltham is now HMYOI Feltham (B side)

### Describe alternatives you've considered

I've looked to see if we could do this ourselves but couldn't see how

### Screenshots or a link to a Loom Recording

![Screenshot (240)](https://github.com/yalla-coop/shannon-trust-website/assets/107695201/22af015e-c95c-4ae5-9f25-a71cdf7051fa)

**Comment by bethanyios** [comment]
Hi @ShannonTrust thanks for letting us know, we will get this change done for you 

cc. @fadeomar

**Comment by fadeomar** [comment]
hey @bethanyios @cyberteenie @ShannonTrust, 
I have finished working on the issue by making the requested changes. The task is now prepared for testing.
staging link: https://shannon-trust.webflow.io/order-resources

**Comment by ShannonTrust** [comment]
Hello,

Just tested and it’s all working fine – please can we make this live, if it’s not already? Many thanks ☺

Kind regards,

Amy Longstaff
Communications and Fundraising Manager

Tel: 020 3764 5251
Mobile: 07561165119
Mailing address: FREEPOST Shannon Trust

***@***.***


Twitter<https://twitter.com/Shannon_Trust> | Facebook<https://www.facebook.com/ShannonTrustCharity/> | Web<http://www.shannontrust.org.uk/> | LinkedIn <https://www.linkedin.com/company/shannon-trust/> | Instagram<https://www.instagram.com/shannontrustcharity/>

Registered address: Shannon Trust, International House, 101 King’s Cross Road, London, WC1X 9LP

Registered Charity no. 1117249

At Shannon Trust we work flexible hours. Please note that if you receive an email from me in the evening or at a weekend there is not an expectation for you to respond outside of your own working hours.

***@***.***    [dc_badge1]     [BITC BanTheBox Logo OnLight]

**Comment by fadeomar** [comment]
hey @ShannonTrust it's deployed now :+1:
