### ISSUE TITLE
Digital impact report

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#98]
### Is your feature / client request related to a problem? Please describe.

Early next year we'd like to have our impact report on our website so that it's interactive. We'd probably want to start working on this around November/December, depending on how long you think it will take to organise/set up.

### Screenshots or a link to a Loom Recording

Example from other charities:

https://www.samaritans.org/about-samaritans/our-organisation/annual-and-impact-reports/our-impact-report/impact-report-2021-2022/

https://www.youngminds.org.uk/about-us/reports-and-impact/impact-report-2022/highlight-tour/

https://girlswhocode.com/2022report/

https://www.treeaid.org/blogs-updates/annual-report-2020-21/

https://www.greenpeace.org.uk/impact/impact-report-2019/

**Comment by cyberteenie** [comment]
@ShannonTrust - I will put you in touch with Fadi and Jem to schedule an initial design thinking workshop so that we ca start thinking about how we want to build this out. Thanks!

**Comment by jema28** [comment]
Hey @cyberteenie, unassigning myself from this as I'll be on leave but @adnan0afana and/or @fadeomar will be able to take this on

**Comment by ShannonTrust** [comment]
Let us know when is a good time to meet and discuss what needs to be done.

**Comment by cyberteenie** [comment]
Hi @ShannonTrust - would next Wednesday morning work for you? 9:30am UK time?

**Comment by ShannonTrust** [comment]
Hi @cyberteenie, yes, that works for me (Megan). I'll be leading on this, so please sent the meeting invite to my personal email

**Comment by cyberteenie** [comment]
@ShannonTrust - ok great! I have just sent through the invite. Please let me know if you have received it. If it comes through as 10:30am, please know that this is because I am an hour ahead of you in Berlin. Thanks!

**Comment by ShannonTrust** [comment]
Thanks, @cyberteenie. I've received it and accepted.

**Comment by cyberteenie** [comment]
Notes from call with Megan:

- Likes Samaritan and Green Peace reports most
- https://www.samaritans.org/about-samaritans/our-organisation/annual-and-impact-reports/our-impact-report/impact-report-2021-2022/we-are-samaritans/
- https://www.greenpeace.org.uk/impact/impact-report-2019/
- Wants to link out to report from Impact page
- Needs dropdown navigation to navigate between different report sections
- Each page should have arrow button so that people can navigate between sections
- The PDF report should be downloadable (as should past reports)
- Keep it simple and accessible, not so many graphics
- Timeline is for everything to be live by the end of January / start of February

Next steps:
- Adnan + I to go through the 2022 PDF report and pull out the sections we understand (https://www.shannontrust.org.uk/impact)
- Send that through to Megan for confirmation, along with a timeline
- Create wireframes
- Create on webflow
- Update numbers for launch of report in early 2024

**Comment by adnan0afana** [comment]
@cyberteenie @ShannonTrust  I've aggregated the pages that can be on one page, we need about 11 pages for 2022 PDF, have a look here and let me know if you have any comments/thoughts
https://www.figma.com/file/vC6iqpWqeTJSPkM0Lswcfp/Shannon-Trust-Website---Design-System-and-Wireframes?type=design&node-id=3034-7402&mode=design&t=gSAjESyYErr6Kbaf-4

**Comment by ShannonTrust** [comment]
Thanks, @adnan0afana. I'm meeting with our CEO about the impact report tomorrow, so I'll let you know if I think there might be any additional pages to this. 

From my point of view though, I think we could have 'about Shannon Trust', 'our values' and 'Shannon Trust's impact in summary' all on one page (this will probably look different in the PDF version, but a lot of this information is already on our website so we don't need to highlight it too much here), and then I'd like to have the 3 different strands of our strategy on different pages (the pages that have 1, 2, 3 on them)

**Comment by adnan0afana** [comment]
Thanks @ShannonTrust so I'll be waiting for your reply
and I liked what are you using, it makes sense, I created a new section with the suggested pages you can [navigate it directly](https://www.figma.com/file/vC6iqpWqeTJSPkM0Lswcfp/Shannon-Trust-Website---Design-System-and-Wireframes?type=design&node-id=3041-6790&mode=design&t=9Jf1lzQ4mDqIQkUW-4)

**Comment by cyberteenie** [comment]
@ShannonTrust - just wanted to check in to see if there were any updates regarding the impact report after the meeting last week? Thanks!

**Comment by ShannonTrust** [comment]
Hi @cyberteenie and @adnan0afana, I've done an outline of the impact report and there will be a few changes:

We're going to add an extra page between page 2 and 3, which will be a brief overview of our strategy and titled 'Our commitments'.

The next 3 pages will stay the same, but then the others have moved order - not sure if that matters at the minute, but I thought I'd let you know everything. This is the order they'll go in:
- Digital developments
- Developing our resources (an additional page)
- Our people (previously developing our workforce)
- Telling our story
- Finances and fundraising
- Thank you

We won't need 'involving our beneficiaries', as that is now being put into the 'our people' section.

Let me know if that doesn't make sense. 

On a side note, I hope everyone based in Gaza is as safe as they can be at the minute. Thinking about you all and if there's anything we can do at Shannon Trust to help, please let us know - Megan.

**Comment by cyberteenie** [comment]
Thanks @ShannonTrust, really appreciate the thoughts.
We will work on the wireframes for this in November and will share that for your confirmation so that we can get this done for you before the new year. Thanks!

**Comment by cyberteenie** [comment]
Hi @ShannonTrust - we are now starting to build out the initial design for the impact report, but I just do have a few questions about how we should link everything up. Maybe this would be best done on a call. What is your availability like this week?

**Comment by ShannonTrust** [comment]
Hi @cyberteenie, not a problem. I can do anytime tomorrow, Thursday I have a meeting at 11.30am for half an hour but can do anytime before or after. Thanks - Megan

**Comment by cyberteenie** [comment]
@ShannonTrust - great! I have just sent through an invite for Thursday at 1pm UK time. See you then!

**Comment by cyberteenie** [comment]
Hi @linaayesh - following Megan and my discussion:
- The preference is for the impact page to have a generalized "Impact Reports" button
- To use the version where people can toggle between the different reports from the report page (defaulting to the most recent report)

There are a few design things which I will link to the prototype as comments.

One other thing to document for development is that the team will need to be able to edit the content and that for future reports, the content / headers / sections may change.

**Comment by cyberteenie** [comment]
Hi @ShannonTrust - here is a [cleaned up version of the "look and feel" of the impact report Megan](https://www.figma.com/proto/vC6iqpWqeTJSPkM0Lswcfp/Shannon-Trust-Website---Design-System-and-Wireframes?page-id=214%3A2&type=design&node-id=3307-11917&viewport=18421%2C1180%2C0.32&t=aZnn4umR5PEAhiiF-1&scaling=scale-down&starting-point-node-id=3101%3A13232&show-proto-sidebar=1&mode=design). We tried to bring it a little bit more in line with the rest of the site design. Feel free to show it to the rest of the team and let us know if you are happy with it.

Like we spoke about if all of the sections every year stick to the same layout, then we can easily design this and you could enter the copy every year as a part of a collection. 

Alternatively, if the sections vary year to year, either we can help with ensuring that everything is on brand, or we can template some sections that can be used when needed. This final solution will be the most resource intensive, but would give you the most flexibility moving forward. Let me know your thoughts!

**Comment by ShannonTrust** [comment]
Thanks, @cyberteenie. I'll take a look at some point today and I've also shared it with Amy, so we'll let you know if we have any comments. I'll also think about the layout going forward and let you know.

**Comment by ShannonTrust** [comment]
@cyberteenie - We've had a look at the wireframes and there's a couple of things we'd like changing if possible:

- Would it be possible to have everything in one width, please? When you briefly showed me the other day, I thought it was in one frame?
- Could the 'next' and 'previous' buttons be smaller and have block colour rather than on the photos, please?
- If those buttons change, we could then have links to the impact page and about us at the bottom instead.
- When you select the year, will it take you down the page to the report? I'm worried that with the photo there people might not scroll down to find it.
- How will the 2022 report appear with it just being a PDF?

Hopefully that all makes sense. 

In regards to your other comment, I'm anticipating that next year will follow a similar layout. If you design it this way, would we easily be able to add new sections that follow a similar pattern? Or will we need you to create something completely different? 

My initial thought is if we can keep it as the same layout each year, that would be easier, but I'd still like us to have a bit of freedom in how that might look incase we want to change something.

**Comment by cyberteenie** [comment]
Hi @ShannonTrust! Thank you for your feedback!
We have made the report one width (it uses the current padding to align with the rest of the site), made the buttons smaller and with block colors, and used the photo buttons to link to the impact page and about us. 

I will double check about the scrolling functionality with the development team!

In regards the the PDF, I was under the impression that this was going to be provided by Shannon Trust but we are happy to work on laying it out in a way that is similar to the site. That time would then also just be taken out of the SLA work. Thanks!

**Comment by ShannonTrust** [comment]
Thanks, @cyberteenie. That's much better, thank you for making the changes.

Sorry, I should've been more clear. We're arranging the design of the PDF, but what I meant was, when you click on the menu to see last year's report, how will that come up with it only being in a PDF format and not digitised for the website?

**Comment by cyberteenie** [comment]
@ShannonTrust - I think that the lean solution is just to put a little notice on that page, that only a PDF version of the report is available for that year and the download button. 

The more advanced solution is to digitise that report as well, but I think we leave that until the end when we can see how much time is remaining. Does that work for you?

**Comment by ShannonTrust** [comment]
Sounds good. Thanks, @cyberteenie.

**Comment by redahaq** [comment]
Hi @ShannonTrust Just confirming that yes, selecting the report year will automatically scroll the page to the top of the report section.

**Comment by ShannonTrust** [comment]
Hey @cyberteenie, I'm attaching the impact report content how it currently stands. It's with our CEO for a review, but I'm hoping it won't change too much. 

Hopefully this is enough to start building it on our website. Any questions, let me know. I'm finishing today and will be back on the 3 January 2024. Thanks for all your help with this so far. Wishing you all a happy holiday season and best wishes for the New Year - Megan.

[Impact report 2023 content v1.docx](https://github.com/yalla-coop/shannon-trust-website/files/13725799/Impact.report.2023.content.v1.docx)

**Comment by cyberteenie** [comment]
Hi @ShannonTrust - thanks for this! Have a lovely holiday and speak to you in the new year!

**Comment by cyberteenie** [comment]
Hi @ShannonTrust - Just wanted to check in to see if the impact report content has been finalised? I think it would also be good to jump on a call to align on how things are displayed. I also wondered about simplifying some bits. 
If you could let me know when would be a good time to meet, that would be much appreciated!

**Comment by ShannonTrust** [comment]
Hi @cyberteenie, there will be a few things that will need to change before it goes live, but it will mostly be to do with the data. The copy should be good to go now though. 

I'm around tomorrow, Friday, Tuesday afternoon or Wednesday afternoon if there's a time there that works for you.

**Comment by cyberteenie** [comment]
@ShannonTrust - ok great! I will send through an invitation for tomorrow afternoon - thanks!

**Comment by cyberteenie** [comment]
@ShannonTrust - just sent one through for 3pm UK time! Do let me know if that works for you!

**Comment by ShannonTrust** [comment]
Hi @cyberteenie and @redahaq, thanks for meeting with me. Here is the link to all the images that you can use for the report https://drive.google.com/drive/folders/1pLaEREIDx1paObOVmVgJHQoYnvhxMAH1?usp=sharing

I've split the copy into sections as discussed, hopefully that makes it easier for you. Let me know if you need anything else or you're unsure about anything.
[Impact report 2023 content website version.docx](https://github.com/yalla-coop/shannon-trust-website/files/13832236/Impact.report.2023.content.website.version.docx)

**Comment by redahaq** [comment]
Hi @ShannonTrust, thanks very much for this Megan - I've added all the text content to the draft reports, but held off on the images so they can align with the PDF. It would be great if you can have a look and provide your feedback. Thank you! https://shannon-trust.webflow.io/impact-reports/impact-report-2023

**Some notes/ questions**
- Some of the chapter headings are quite long, we think it would be good if they can be shortened if possible. What do you think?

- I modified the heading for chapter 2 slightly from 'Who we are', to 'Who we are, impact and commitments' as it covers a few different topics

- Is there some updated text we can use for these 2 cards?
<img width="802" alt="Screenshot 2024-01-18 at 14 34 20" src="https://github.com/yalla-coop/shannon-trust-website/assets/39345463/458cccbd-a5b8-466f-b4ff-cee5c1143bd0">

cc. @cyberteenie

**Comment by ShannonTrust** [comment]
Thanks, @redahaq. I've had a quick scan and it's looking good. I'll have a proper look through tomorrow and let you know of any comments. We also now how the first draft of the PDF back, but we're hoping to get some new photography next week to swap in. I'll let you know as soon as possible if that's going to happen.

**Comment by ShannonTrust** [comment]
Hi @redahaq, I've had another look and I have some comments, but I'm going to hold off for a week or so because I'm waiting for the team to come back to me for edits for the PDF. That way we can align the website and PDF. I'll get back to you soon.

**Comment by redahaq** [comment]
@ShannonTrust Thanks Megan! Is there perhaps any functionality-related feedback you have, that I can maybe look at this week? I have a project starting on Monday so I have a bit more capacity this week to get ahead of things this week, if possible. No worries if not.

**Comment by ShannonTrust** [comment]
Hi @redahaq, the only thing I've been thinking about is the long chapter headings. It's going to be hard to shorten chapters 3, 4 and 5, as they are the strands of our strategy. But I wonder if an alternative would be to title the chapters commitment 1, commitment 2, commitment 3, and then the full title acts as a subheading when you're in that chapter. Does that make sense? 

I don't know if the 2 cards pictured above will be relevant. We have a couple of extra stats to add in to the purple box, but we could probably remove the grey boxes.

**Comment by redahaq** [comment]
@ShannonTrust  Thanks for getting back to me Megan, that's good to know. Let's keep the headings as they stand in that case. And noted about the boxes. Thank you!

**Comment by cyberteenie** [comment]
@ShannonTrust - just wanted to see if the PDF was ready to share now? I know we were looking to have the impact report live this month if possible!

**Comment by ShannonTrust** [comment]
Hi @cyberteenie, the PDF isn't quite ready yet. I'm sending back some notes to the designer today following the first draft. The aim is to have the impact report live mid February as we won't have all our data for another week or so. I'll send the PDF as soon as it's ready.

**Comment by ShannonTrust** [comment]
Hi @cyberteenie and @redahaq, sorry this has taken so long to get to you, we had to push the date back as we didn't have all the final data. This is pretty much the final version of the PDF so you know what photos go with each section - all photos are in the Google Drive linked above.

Would you be able to give me a rough idea of when you'll be able to make the changes to the website, please? Some of the copy has been edited, so I can go through and change this once the design is finished.

Thank you.

[Shannon Trust - Impact report 2023 v4 2.pdf](https://github.com/yalla-coop/shannon-trust-website/files/14328708/Shannon.Trust.-.Impact.report.2023.v4.2.pdf)

**Comment by cyberteenie** [comment]
Morning @ShannonTrust - thank you! 
Is there a date when you need it by? Let me speak to the team and check in with resourcing!

**Comment by ShannonTrust** [comment]
Thanks, @cyberteenie. As soon as possible really, but I understand you'll have other deadlines going on. We're planning on sending the impact report out next week, so if you can do the changes by Monday, that would be incredible, but we will have the PDF if that is an ambitious target.

**Comment by redahaq** [comment]
Hi @ShannonTrust. Thanks so much for sharing the PDF, very exciting. I hope to get on this in the latter half of this week and will try my best to work to the Monday deadline; will send you an update Thurs eve/ Fri am on how things are shaping up. I haven't gone through properly yet, but do you have images of the charts that you can add to the google drive folder as well, please? Thanks so much! cc @cyberteenie

**Comment by ShannonTrust** [comment]
Thanks, @redahaq, really appreciate it. I don't have the charts at the minute (one of them still needed a couple of edits), but I'm hoping I'll get all the files by the end of the week. I'll keep you updated. If I don't have them before Monday, please can you put a placeholder where they're supposed to go and I'll add them in once I've received everything. Thank you.

**Comment by redahaq** [comment]
Hi @ShannonTrust @cyberteenie. I've been making good progress on the reports. It's not quite ready for a full review yet - 
but if you wanted to have a peek, it's here. https://shannon-trust.webflow.io/impact-reports/impact-report-2023#chapter-top

I've been making some copy changes where I see them.

Outstanding issues:

- [ ] - add pdfs to download pdf buttons for 2023 and 2022
- [ ] - fix subheading text font size and style
- [ ] - fix background width and white space above next/prev buttons container
- [ ] - remove whitespace between sections
- [ ] - check stats alignment
- [ ] - check responsive
- [ ] - finish adding alt tags for images
- [ ] - review copy for changes

If you'd like to highlight anything else, please leave a comment below. 

**I'd ask if you could hold off making edits yourself for now, so we don't run into conflicts if that's ok?**

If you have the charts tomorrow I can add them in for you as well. I'll be resuming work on this midday/1pm tomorrow, so I can pick up then! Thank you.

**Comment by ShannonTrust** [comment]
Thanks, @redahaq. It's looking good. I've added the charts into the Google Drive folder. 

A couple of initial comments:

- For the introduction, can we just have the text with no images, please? 
- Could we include Patrick's learner story underneath 'our impact in 2023'? - I think this makes sense and we can reduce how many pages we have
- For some reason the photo on 'our commitments' is blurry, do you know why this is?
- Under '1. Increase the number of people completing our reading programme in prisons' can you swap the photo to the facilitators team photo, please?
- Could you remove Ben's mentor story, please?
- In the 'telling our story' section, can you remove the first photo, please?

**Comment by redahaq** [comment]
Thanks @ShannonTrust I'm working through making these changes. 

Given you said there had been some chart edits, is the 2023 report pdf you sent us the final version, that we can use for the download PDF button, or is there a newer version you can share please? Thank you!

**Comment by redahaq** [comment]
@ShannonTrust  Re. the 'our commitments' blurry image - the image sizes were sometimes too large for webflow so I had to compress them, this shouldn't affect the quality but I think you're right that one is definitely blurry. Is there an alternative image you'd be happy to use in its place?

**Comment by ShannonTrust** [comment]
Hi @redahaq, what size do you need the image to be? I can change it in Photoshop so it can fit better. 

I've got a couple more edits to make to the PDF, but I can add that in last minute as I won't be able to make the changes until Monday morning now. Some of the figures have changed last minute, so if you've added it in already, the 'new learner' chart will need to be updated - I've added the latest version to Google Drive.

**Comment by redahaq** [comment]
@ShannonTrust Thank you, it needs to be under 4mb, either jpg or png is fine.

Would you also be able to send the table under the pie charts as an image please?

I'll update the chart. I've made all the other changes and am just going through each chapter now to update the copy.

**Comment by ShannonTrust** [comment]
@redahaq I've reduced the size of the image so hopefully that works better now, if not, I'll have a look at what we can replace it with. 

Thanks for all you help so far and for getting it done so quickly - sorry again for the tight deadline. I'll finalise the PDF on Monday morning and then I'll look at any final copy changes on the web version before it goes live.

Have a lovely weekend.

**Comment by redahaq** [comment]
@ShannonTrust wonderful, thank you. My pleasure. Good luck with getting it all finalised! Hope you don't have too much left to do. Hope you have a lovely weekend too.

**Comment by ShannonTrust** [comment]
Hi @redahaq, here is the final PDF. Am I OK to go through and make any copy edits now?

[Shannon Trust Impact Report 2023.pdf](https://github.com/yalla-coop/shannon-trust-website/files/14404091/Shannon.Trust.Impact.Report.2023.pdf)

**Comment by redahaq** [comment]
Hey @ShannonTrust , I've fixed the gaps on:
- Increase the number of people completing our reading programme in prisons
- Digital developments

**Comment by ShannonTrust** [comment]
Thanks, @redahaq. I tried a couple of different photos on 'our commitments' but it was coming out blurry every time - even though it was fine in Webflow. I've decided to delete it for now so we can be ready to share the report tomorrow. 

I think that's everything for now, but it would be great if you could show us at some point how we can recreate this format for our report next year?

**Comment by redahaq** [comment]
@ShannonTrust ah right, thanks for trying, that is strange - I'll do a quick try of deleting that image placeholder completely and re-adding to see if that fixes it. If it doesn't, I'll remove it, as you've described. 

Yes of course, I'd be happy to go through how to recreate.

**Comment by redahaq** [comment]
@ShannonTrust  I think the image looks sharp now (Our commitments chapter), but please let me know if you still see issues and I can remove it.

**Comment by ShannonTrust** [comment]
@redahaq that looks much better, thanks so much!

**Comment by redahaq** [comment]
Any time. Glad we got it working! :)

**Comment by ShannonTrust** [comment]
Closing this now as it's all complete and live. Thanks again @redahaq for all your work on this :) Like I mentioned before, if we can have some guidance on how to recreate the impact report for next year, that would be great. Thank you!
