### ISSUE TITLE
New volunteer role to be added to volunteer page and form

### ISSUE THREAD

**Issue by ShannonTrust** [yalla-coop/shannon-trust-website#99]
### Is your feature / client request related to a problem? Please describe.

We are introducing a new volunteer role and need to add it to the website

### Describe the solution you'd like

New role to be added under the 'In the community' section (https://www.shannontrust.org.uk/volunteer)

**Community project support**
As community project support, you will support and coordinate a team of community reading coaches to work directly with people with low literacy. You will support with recruitment and training of volunteers, as well as coordination of the delivery of our digital tool, Turning Pages Digital, to support people on probation in Kent, Surrey and Sussex to improve their literacy skills. 

View role description 
[Community project support role description.docx](https://github.com/yalla-coop/shannon-trust-website/files/12549410/Community.project.support.role.description.docx)

Check locations and apply (link to form)

For the form, can it follow the same structure as the 'area coordinator' role and just change the criminal record declaration to the following:
As a Shannon Trust community volunteer, you may be visiting probation offices and have contact with people on probation. His Majesty's Prison and Probation Service requires those accessing information related to people on probation to complete BPSS clearance. Please therefore declare below ANY previous criminal convictions (excluding speeding endorsements and parking offences). Having a criminal conviction does not necessarily exclude you from volunteering with us.

The locations for this role are:
Surrey
West Sussex
East Sussex
East Kent
Central Kent
West Kent

**Comment by ShannonTrust** [comment]
I've been asked by our community team if this can please be added to the website by the end of next week if at all possible. Thank you.

**Comment by adnan0afana** [comment]
Hey @RamyAlshurafa can you have a look at this

**Comment by RamyAlshurafa** [comment]
done @ShannonTrust 
Can you check and let me know if any questions?

**Comment by ShannonTrust** [comment]
Thanks, @RamyAlshurafa. It looks good on our end and happy for it to go live on the main site. Thank you.

**Comment by RamyAlshurafa** [comment]
no worries, thats been deployed to the main site now
